-- macro_controller.lua  ─  sim-derived build order, executed distributed (COR)
--
-- The whole economy is one ordered blueprint (blueprints/general/build_order_blueprint.lua,
-- generated by build_order_sim.py + blueprint_gen.py).  blueprint_placer's distributed
-- mode runs it with several builders at once: each idle builder claims the lowest-index
-- item it can build, and leaves a frame at 85% as soon as a finished nano turret can
-- complete it.  That keeps a fresh nanoframe standing at all times, which is what the
-- nanos need to stay busy.
--
-- Hard-coded early game (the rest is emergent):
--   1. The commander is the only builder, so it places wind, wind, corlab, mex, wind, wind.
--   2. The lab's first con bot joins the queue and reaches nano #1 first (the commander
--      cannot build nano turrets).  The commander then GUARDs that con so it assists
--      nanos #1 and #2 instead of running ahead.
--   3. After 2 nanos the commander rejoins the pool.  Con bot #2 is queued 60 s after
--      con #1 finished (the sim's CON_GAP), and the lab is reclaimed once it exists —
--      that refund is part of the build order, not an afterthought.

local widget = widget
local Spring = Spring
local CMD    = CMD

local spGetUnitPosition = Spring.GetUnitPosition
local spGetUnitDefID    = Spring.GetUnitDefID
local spGiveOrderToUnit = Spring.GiveOrderToUnit
local spGetMyTeamID     = Spring.GetMyTeamID

local CMD_GUARD = (CMD and CMD.GUARD) or 25
local CMD_STOP  = 0

-- Con bot #2 trails #1 by this much; mirrors CON_GAP in build_order_sim.py.
local CON_GAP_FRAMES  = 60 * 30
local NANO_ASSIST_NUM = 2     -- nanos the commander assists the con through
-- The blueprint's first wind sits almost on top of the anchor, and the bot lab sits
-- 64 elmos north of it, so anchoring on the commander means the engine shoves the
-- commander aside before it can build.  Offsetting the blueprint diagonally clears
-- the commander's spawn of both, while keeping every early item inside its build
-- range (~152 elmos to a wind) so it never has to walk to place them.
local ANCHOR_OFFSET_X = 64
local ANCHOR_OFFSET_Z = 64
local START_FRAME     = 15    -- orders issued at frame 0 are dropped by the engine

function widget:GetInfo()
    return {
        name    = "Macro Controller",
        desc    = "Distributed sim build order (COR)",
        author  = "",
        date    = "2026",
        license = "GNU GPL, v3 or later",
        layer   = 0,
        enabled = true
    }
end

local DEBUG = false

-- ── Loaded in Initialize ──────────────────────────────────────────────────────
local BP_PLACER   = nil
local BUILD_ORDER = nil

-- ── State ─────────────────────────────────────────────────────────────────────
local myTeamID    = nil
local commanderID = nil
local botLabID    = nil
local baseX, baseZ = nil, nil
local currentFrame = 0

local distState     = nil
local startPending  = false   -- anchor known, waiting for START_FRAME
local conBot1ID     = nil
local conCount      = 0       -- con bots finished
local pendingCons   = {}      -- unitID -> true while still inside the lab
local conDefID      = nil
local con2Frame     = nil     -- frame at which con #2 gets queued
local con2Queued    = false
local nanoAssistDone = false
local comGuardTarget = nil    -- unitID the commander is currently guarding
local labReclaimGated = true  -- hold the reclaim step until con #2 exists

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function IsCommander(uDefID)
    local d = uDefID and UnitDefs[uDefID]
    if not d then return false end
    return d.customParams ~= nil
        and (d.customParams.iscommander ~= nil or d.customParams.is_commander ~= nil)
end

local function IsGroundCon(d)
    return d ~= nil and d.isBuilder and not d.canFly and not d.isFactory
       and d.speed and d.speed > 0
end

local function FindConBotDefID(labDefID)
    local d = UnitDefs[labDefID]
    if not d or not d.buildOptions then return nil end
    local best, bestCost = nil, math.huge
    for _, optID in ipairs(d.buildOptions) do
        local od = UnitDefs[optID]
        if IsGroundCon(od) then
            local cost = od.metalCost or 999999
            if cost < bestCost then bestCost = cost; best = optID end
        end
    end
    return best
end

local function StopGuard()
    if comGuardTarget and commanderID and spGetUnitDefID(commanderID) then
        spGiveOrderToUnit(commanderID, CMD_STOP, {}, {})
    end
    comGuardTarget = nil
end

local function Guard(targetID)
    if comGuardTarget == targetID then return end
    spGiveOrderToUnit(commanderID, CMD_GUARD, {targetID}, {})
    comGuardTarget = targetID
    if DEBUG then Spring.Echo("[MC] commander guards " .. tostring(targetID)) end
end

-- ── Blueprint start ───────────────────────────────────────────────────────────

local function StartBuildOrder()
    local cx, _, cz = spGetUnitPosition(commanderID)
    if not cx then return end
    baseX = math.floor(cx / 16 + 0.5) * 16 + ANCHOR_OFFSET_X
    baseZ = math.floor(cz / 16 + 0.5) * 16 + ANCHOR_OFFSET_Z
    startPending = true
    if DEBUG then Spring.Echo("[MC] anchor " .. baseX .. "," .. baseZ) end
end

local function BeginBuildOrder()
    distState = BP_PLACER.NewDistributed(BUILD_ORDER, baseX, baseZ, 0)
    BP_PLACER.AddBuilder(distState, commanderID)
    startPending = false
    if DEBUG then
        Spring.Echo("[MC] build order started, " .. #distState.queue .. " items")
    end
end

-- ── Phase logic ───────────────────────────────────────────────────────────────

-- The reclaim step sits right after nano #2 in the build order, but reclaiming
-- the lab before con bot #2 has rolled out would cost us that con entirely.
local function GateLabReclaim(frame)
    if not labReclaimGated then return end
    for i = 1, #distState.queue do
        local item = distState.queue[i]
        if item.act == "reclaim" then
            if conCount >= 2 then
                item.deferUntil  = nil
                labReclaimGated  = false
                if DEBUG then Spring.Echo("[MC] lab reclaim released") end
            else
                item.deferUntil = frame + 300
            end
            return
        end
    end
    labReclaimGated = false   -- no reclaim step in this blueprint
end

local function UpdateCommanderPhase(frame, resources)
    if not commanderID or not spGetUnitDefID(commanderID) then
        commanderID = nil
        return
    end

    -- Whatever we were guarding is gone (con died, lab reclaimed) — GUARD has
    -- already self-terminated, so take the commander back.
    if comGuardTarget and not spGetUnitDefID(comGuardTarget) then
        comGuardTarget = nil
        BP_PLACER.AddBuilder(distState, commanderID)
    end

    if not nanoAssistDone then
        if BP_PLACER.CountBuilt(distState, "nano") >= NANO_ASSIST_NUM then
            nanoAssistDone = true
            StopGuard()
            BP_PLACER.AddBuilder(distState, commanderID)
            if DEBUG then Spring.Echo("[MC] nano assist done, commander rejoins pool") end
        elseif conBot1ID and spGetUnitDefID(conBot1ID) then
            local claim = BP_PLACER.GetClaim(distState, conBot1ID)
            -- Only hand over between items, so the commander never abandons a
            -- frame that has no nano in range to finish it.
            if claim and claim.cls == "nano"
               and BP_PLACER.GetClaim(distState, commanderID) == nil then
                BP_PLACER.RemoveBuilder(distState, commanderID)
                Guard(conBot1ID)
            end
            return
        end
    end

    if comGuardTarget == conBot1ID and comGuardTarget ~= nil then return end

    -- Nothing the commander can build right now (typically the next item is a
    -- nano): assist the lab so the next con bot comes out sooner.
    local hasWork = BP_PLACER.GetClaim(distState, commanderID) ~= nil
                 or BP_PLACER.HasClaimable(distState, commanderID, frame, resources)
    if hasWork then
        if comGuardTarget == botLabID and comGuardTarget ~= nil then
            StopGuard()
            BP_PLACER.AddBuilder(distState, commanderID)
        end
    elseif botLabID and spGetUnitDefID(botLabID) and comGuardTarget == nil then
        BP_PLACER.RemoveBuilder(distState, commanderID)
        Guard(botLabID)
    end
end

-- ── Widget callbacks ──────────────────────────────────────────────────────────

function widget:Initialize()
    local ok1, r1 = pcall(VFS.Include, "LuaUI/Widgets/blueprint_placer.lua")
    local ok2, r2 = pcall(VFS.Include,
        "LuaUI/Widgets/blueprints/general/build_order_blueprint.lua")
    if not ok1 then Spring.Echo("[MC] ERROR loading blueprint_placer: "      .. tostring(r1)); return end
    if not ok2 then Spring.Echo("[MC] ERROR loading build_order_blueprint: " .. tostring(r2)); return end
    BP_PLACER   = r1
    BUILD_ORDER = r2

    if DEBUG then
        -- Real footprints, to check them against the sizes blueprint_gen assumed.
        for _, n in ipairs({"corwin", "cormex", "cornanotc", "corlab", "corck"}) do
            local ud = UnitDefNames[n]
            if ud then
                Spring.Echo(string.format("[MC] def %s xsize=%s zsize=%s buildDist=%s",
                    n, tostring(ud.xsize), tostring(ud.zsize), tostring(ud.buildDistance)))
            end
        end
    end

    myTeamID = spGetMyTeamID()
    for _, uid in ipairs(Spring.GetTeamUnits(myTeamID) or {}) do
        if IsCommander(spGetUnitDefID(uid)) then
            commanderID = uid
            break
        end
    end
    if commanderID then StartBuildOrder() end
end

function widget:UnitCreated(unitID, unitDefID, teamID, builderID)
    if not myTeamID then myTeamID = spGetMyTeamID() end
    if teamID ~= myTeamID then return end

    -- Must come first: the corlab is itself a queue item, and so is anything
    -- else that would hit an early return below.
    if distState then
        BP_PLACER.OnUnitCreated(distState, unitID, unitDefID, builderID)
    end

    local d = UnitDefs[unitDefID]
    if not d then return end

    if d.isFactory and not botLabID then
        botLabID = unitID
        if DEBUG then Spring.Echo("[MC] bot lab " .. unitID) end
        return
    end

    -- Con bots start life inside the lab; they are only usable once finished.
    if builderID and builderID == botLabID and IsGroundCon(d) then
        pendingCons[unitID] = true
    end
end

function widget:UnitFinished(unitID, unitDefID, teamID)
    if teamID ~= myTeamID then return end

    if IsCommander(unitDefID) and not commanderID then
        commanderID = unitID
        StartBuildOrder()
    end

    -- Lab done → queue con bot #1.  Con #2 is queued CON_GAP_FRAMES after #1
    -- finishes, which is the spacing the sim's build order assumes.
    if unitID == botLabID then
        conDefID = FindConBotDefID(unitDefID)
        if conDefID then spGiveOrderToUnit(botLabID, -conDefID, {0}, {}) end
        if DEBUG then Spring.Echo("[MC] lab finished, con #1 queued") end
    end

    if pendingCons[unitID] then
        pendingCons[unitID] = nil
        conCount = conCount + 1
        if not conBot1ID then
            conBot1ID = unitID
            con2Frame = currentFrame + CON_GAP_FRAMES
        end
        BP_PLACER.AddBuilder(distState, unitID)
        if DEBUG then Spring.Echo("[MC] con #" .. conCount .. " joined (" .. unitID .. ")") end
    end

    if distState then
        local x, _, z = spGetUnitPosition(unitID)
        BP_PLACER.OnUnitFinished(distState, unitID, unitDefID, x, z)
    end
end

function widget:UnitDestroyed(unitID, unitDefID, teamID)
    if teamID ~= myTeamID then return end
    if DEBUG then
        local x, _, z = spGetUnitPosition(unitID)
        Spring.Echo(string.format("[MC] lost %s id=%s at (%s,%s) f=%d beingBuilt=%s",
            UnitDefs[unitDefID] and UnitDefs[unitDefID].name or "?", tostring(unitID),
            tostring(x and math.floor(x)), tostring(z and math.floor(z)),
            currentFrame, tostring(Spring.GetUnitIsBeingBuilt(unitID))))
    end
    if distState then BP_PLACER.OnUnitDestroyed(distState, unitID) end
    pendingCons[unitID] = nil
    if unitID == commanderID then commanderID = nil end
    if unitID == conBot1ID   then conBot1ID   = nil end
    if unitID == botLabID    then botLabID    = nil end
    if unitID == comGuardTarget then comGuardTarget = nil end
end

function widget:GameFrame(frame)
    currentFrame = frame
    if not myTeamID or not BP_PLACER then return end

    if startPending and frame >= START_FRAME then BeginBuildOrder() end
    if not distState then return end

    -- Con bot #2, one CON_GAP after con #1 finished.
    if not con2Queued and con2Frame and frame >= con2Frame then
        if botLabID and spGetUnitDefID(botLabID) and conDefID then
            spGiveOrderToUnit(botLabID, -conDefID, {0}, {})
            con2Queued = true
            if DEBUG then Spring.Echo("[MC] con #2 queued at frame " .. frame) end
        elseif not botLabID then
            con2Queued = true   -- lab gone; nothing to queue from
        end
    end

    if frame % 10 ~= 0 then return end

    local _, m,  ms  = pcall(Spring.GetTeamResources, myTeamID, "metal")
    local _, em, ems = pcall(Spring.GetTeamResources, myTeamID, "energy")
    local resources = {
        metal  = m  or 0, metalStorage  = ms  or 1000,
        energy = em or 0, energyStorage = ems or 1000,
    }

    GateLabReclaim(frame)
    -- Phases first: the commander must be out of the builder pool before
    -- Update hands it a claim it is about to abandon.
    UpdateCommanderPhase(frame, resources)

    if not distState.done then
        BP_PLACER.Update(distState, frame, resources)
    end
end
