-- macro_controller.lua  ─  sim-derived build order, executed distributed (COR)
--
-- The whole economy is one ordered blueprint (blueprints/general/build_order_blueprint.lua,
-- generated by build_order_sim.py + blueprint_gen.py).  blueprint_placer's distributed
-- mode runs it with several builders at once: each idle builder claims the lowest-index
-- item it can build, and leaves a frame at 85% as soon as a finished nano turret can
-- complete it.  That keeps a fresh nanoframe standing at all times, which is what the
-- nanos need to stay busy.
--
-- Hard-coded early game (the rest is emergent):
--   1. The commander is the only builder, so it places wind, wind, corlab, mex, wind, wind.
--   2. The lab's first con bot joins the queue and reaches nano #1 first (the commander
--      cannot build nano turrets).  The commander then GUARDs that con so it assists
--      nanos #1 and #2 instead of running ahead.
--   3. After 2 nanos the commander rejoins the pool.  Con bot #2 is queued 60 s after
--      con #1 finished (the sim's CON_GAP), and the lab is reclaimed once it exists —
--      that refund is part of the build order, not an afterthought.
--
-- HAND-OFF.  The build order is a kick-starter, planned to ~4.5 game-min.  Past that
-- the bot earns faster than it can place, and metal starts banking (measured: surplus
-- at frame ~8100, metal binned from ~9000).  When that happens it puts an air lab up
-- inside the existing nanos' reach -- so it is finished in seconds, not flown to --
-- and from there the grid system takes over: air cons each run a mex_grid_alab
-- blueprint, expanding outward one grid cell at a time.

local widget = widget
local Spring = Spring
local CMD    = CMD

local spGetUnitPosition = Spring.GetUnitPosition
local spGetUnitDefID    = Spring.GetUnitDefID
local spGiveOrderToUnit = Spring.GiveOrderToUnit
local spGetMyTeamID     = Spring.GetMyTeamID
local spGetGroundHeight = Spring.GetGroundHeight
local spGetUnitCommands = Spring.GetUnitCommands
local spGetTeamUnits    = Spring.GetTeamUnits

local CMD_GUARD  = (CMD and CMD.GUARD)  or 25
local CMD_REPAIR = (CMD and CMD.REPAIR) or 40
local CMD_STOP   = 0

-- Con bot #2 trails #1 by this much; mirrors CON_GAP in build_order_sim.py.
local CON_GAP_FRAMES  = 60 * 30
local NANO_ASSIST_NUM = 2     -- nanos the commander assists the con through
-- The blueprint's first wind sits almost on top of the anchor, and the bot lab sits
-- 64 elmos north of it, so anchoring on the commander means the engine shoves the
-- commander aside before it can build.  Offsetting the blueprint diagonally clears
-- the commander's spawn of both, while keeping every early item inside its build
-- range (~152 elmos to a wind) so it never has to walk to place them.
-- Chosen by checking every offset against the actual layout: this is the one where
-- nothing lands on the commander and 10 of the first 12 items are inside its build
-- range.  Re-check it when the build order is regenerated.
local ANCHOR_OFFSET_X = -96
local ANCHOR_OFFSET_Z = -48

-- Hand-off: metal sitting above this share of storage for this long means the build
-- order can no longer spend what the economy earns.  The guards matter — the game
-- STARTS with storage full and no income at all, so the bank test alone fires at
-- frame 0.  Real banking only counts once the economy is actually running.
-- Banking 2k metal already means energy and build power should have been scaled
-- earlier, so hand over on the first clear sign of surplus rather than a full store.
-- The income test is what rules out the start of the game, where storage is full but
-- nothing is being produced.
local BANK_FRAC          = 0.20
local BANK_HOLD          = 150    -- frames (5 s)
local HANDOFF_MIN_INCOME = 40     -- m/s: proves this is income, not the starting stock
local AIR_LAB_MIN_NANOS = 2   -- nanos that must cover the air lab's spot
-- One air con runs a whole grid, so its travel between sites is the bottleneck.
-- Leave each frame this far along for the grid's nanos to finish, and fly on.
local GRID_HANDOFF      = 0.30

-- Retrofit: a finished mex grid is upgraded in place to T2 mexes + fusions by a
-- T2 air con.  The grid's own nanos assist, so build power that would otherwise
-- idle in a finished grid goes back to work, and T2 mexes raise income per unit
-- -- which matters once the unit cap, not metal, is the ceiling.
local UPGRADE_CONS_PER_LAB = 2     -- T2 air cons each advanced air lab builds
-- T2 mexes are LESS metal-efficient than T1, so a retrofit must never compete
-- with a normal grid for metal: while stalling, retrofit builders are stopped.
local RETROFIT_STALL_FRAC  = 0.15  -- stalling below this share of metal storage
local RETROFIT_RESUME_FRAC = 0.30  -- resume once comfortably above it
local START_FRAME     = 15    -- orders issued at frame 0 are dropped by the engine

-- Nano build power is split between two jobs: assisting a factory (its output is
-- units, so that is ARMY spending) and building structures (ECO spending).  Nanos
-- are the bulk of the build power, so this split is what actually decides how much
-- army the bot makes.
local ARMY_SHARE      = 0.30   -- target share of nano build power spent on army
local ARMY_CAP_SLACK  = 1000   -- unit headroom below this -> everything to army
local NANO_REBALANCE  = 30     -- frames between rebalances
local NANO_MOVES_MAX  = 4      -- nanos reassigned per rebalance, to avoid thrash

function widget:GetInfo()
    return {
        name    = "Macro Controller",
        desc    = "Distributed sim build order (COR)",
        author  = "",
        date    = "2026",
        license = "GNU GPL, v3 or later",
        layer   = 0,
        enabled = true
    }
end

local DEBUG = false

-- ── Loaded in Initialize ──────────────────────────────────────────────────────
local BP_PLACER   = nil
local BUILD_ORDER = nil

-- ── State ─────────────────────────────────────────────────────────────────────
local myTeamID    = nil
local commanderID = nil
local botLabID    = nil
local baseX, baseZ = nil, nil
local currentFrame = 0

local distState     = nil
local startPending  = false   -- anchor known, waiting for START_FRAME
local conBot1ID     = nil
local conCount      = 0       -- con bots finished
local pendingCons   = {}      -- unitID -> true while still inside the lab
local pendingStops  = {}      -- {unitID, fireFrame}: deferred CMD_STOP orders
local conDefID      = nil
local con2Frame     = nil     -- frame at which con #2 gets queued
local con2Queued    = false
local nanoAssistDone = false
local comGuardTarget = nil    -- unitID the commander is currently guarding
local labReclaimGated = true  -- hold the reclaim step until con #2 exists

-- ── Hand-off / grid expansion ────────────────────────────────────────────────
local MEX_GRID_BP     = nil
local GRID_SPACING    = nil
local bankFrames      = 0
local handoffStarted  = false
local airLabDefID     = nil
local airLabID        = nil
local airLabItem      = nil   -- the queue item for the hand-off lab
local airLabFrame     = nil   -- frame it was queued, for the watchdog below
local airLabWarned    = false
local airLabRetries   = 0
local airConDefID     = nil
local gridStates      = {}    -- one single-builder placer state per grid
local freeAirCons     = {}    -- air cons waiting for a grid
local pendingGrids    = {}    -- {anchorX, anchorZ, rotation} waiting for an air con
local assignedAnchors = {}    -- "x,z" -> true, every cell ever claimed
local completedAnchors = {}   -- {anchorX, anchorZ} list for FindAllValidPlacements
local completedKeys   = {}
local gridRotation    = {}    -- "x,z" -> rotation the grid was placed with
local UPGRADE_BP      = nil
local upgradeStates   = {}    -- retrofit placer states
local upgradedKeys    = {}    -- grids already assigned a retrofit
local gridFinished    = {}    -- grids whose own build order is COMPLETE
local freeT2Cons      = {}    -- T2 air cons waiting for a grid to upgrade
local retrofitPaused  = false

-- ── Nano army/eco split ──────────────────────────────────────────────────────
local factories   = {}    -- unitID -> true, every finished factory we own
local armyNanos   = {}    -- unitID -> factoryID it was assigned to assist
local lastArmyLog = nil

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function IsCommander(uDefID)
    local d = uDefID and UnitDefs[uDefID]
    if not d then return false end
    return d.customParams ~= nil
        and (d.customParams.iscommander ~= nil or d.customParams.is_commander ~= nil)
end

local function IsGroundCon(d)
    return d ~= nil and d.isBuilder and not d.canFly and not d.isFactory
       and d.speed and d.speed > 0
end

local function FindConBotDefID(labDefID)
    local d = UnitDefs[labDefID]
    if not d or not d.buildOptions then return nil end
    local best, bestCost = nil, math.huge
    for _, optID in ipairs(d.buildOptions) do
        local od = UnitDefs[optID]
        if IsGroundCon(od) then
            local cost = od.metalCost or 999999
            if cost < bestCost then bestCost = cost; best = optID end
        end
    end
    return best
end

-- A factory that can build a flying constructor.  Faction-agnostic: ask the unit
-- defs rather than hard-coding "corap".
-- The cheapest air factory that at least one builder we ACTUALLY OWN can place.
-- Asking only the commander (or falling back to a hard-coded name) can pick a def
-- none of our builders can build: the placer then never claims it, and the item
-- sits in the queue forever without a word.
local function FindAirFactoryDefID()
    local candidates = {}
    if commanderID and spGetUnitDefID(commanderID) then
        candidates[#candidates + 1] = commanderID
    end
    for _, b in ipairs((distState and distState.builders) or {}) do
        candidates[#candidates + 1] = b
    end

    local best, bestCost = nil, math.huge
    for _, uid in ipairs(candidates) do
        local bdID = spGetUnitDefID(uid)
        local bd   = bdID and UnitDefs[bdID]
        if bd and bd.buildOptions then
            for _, optID in ipairs(bd.buildOptions) do
                local od = UnitDefs[optID]
                if od and od.isFactory and od.buildOptions then
                    for _, subID in ipairs(od.buildOptions) do
                        local sd = UnitDefs[subID]
                        if sd and sd.isBuilder and sd.canFly and not sd.isFactory then
                            local cost = od.metalCost or math.huge
                            if cost < bestCost then bestCost = cost; best = optID end
                            break
                        end
                    end
                end
            end
        end
    end
    return best
end

local function FindAirConDefID(labDefID)
    local d = labDefID and UnitDefs[labDefID]
    if not d or not d.buildOptions then return nil end
    for _, optID in ipairs(d.buildOptions) do
        local od = UnitDefs[optID]
        if od and od.isBuilder and od.canFly and not od.isFactory then return optID end
    end
    return nil
end

-- Somewhere for the air lab that the nanos we already own can reach: the point is
-- for it to go up immediately, not for a con to fly out and build it alone.
-- Half-extent of a def's footprint in elmos (xsize counts 8-elmo half-cells).
local function HalfExtent(defID)
    local ud = defID and UnitDefs[defID]
    if not ud then return 0 end
    return math.max((ud.xsize or 0) * 8, (ud.zsize or ud.ysize or 0) * 8) / 2
end

-- Does this spot collide with anything the build order still intends to place?
-- The kickstarter is usually still filling in when the hand-off fires, so a spot
-- that is free right now can be built over minutes later -- which is exactly how
-- the air lab ended up skipped.
local function ClashesWithBuildOrder(cx, cz, half)
    if not (BUILD_ORDER and BUILD_ORDER.layout) then return false end
    for _, u in ipairs(BUILD_ORDER.layout) do
        if u.a ~= "reclaim" then
            local ud = UnitDefNames[u.n]
            if ud then
                local h = HalfExtent(ud.id)
                if math.abs(cx - (baseX + u.x)) < half + h
                   and math.abs(cz - (baseZ + u.z)) < half + h then
                    return true
                end
            end
        end
    end
    return false
end

local function FindAirLabSpot()
    if not airLabDefID then return nil end
    local labHalf = HalfExtent(airLabDefID)
    local bestX, bestZ, bestNanos = nil, nil, -1
    for r = 96, 560, 48 do
        for a = 0, 11 do
            local ang = a * math.pi / 6
            -- Snap through the placer so the lab lands on a legal build position
            -- for ITS footprint, not just a multiple of 16.
            local x, z = BP_PLACER.SnapToBuildGrid(airLabDefID,
                             baseX + r * math.cos(ang), baseZ + r * math.sin(ang))
            local y = spGetGroundHeight(x, z) or 0
            local ok = Spring.TestBuildOrder(airLabDefID, x, y, z, 0)
            if ok and ok ~= 0 and not ClashesWithBuildOrder(x, z, labHalf) then
                local n = BP_PLACER.CountNanosInRange(x, z)
                if n > bestNanos then bestX, bestZ, bestNanos = x, z, n end
                if n >= AIR_LAB_MIN_NANOS then return x, z, n end
            end
        end
    end
    return bestX, bestZ, bestNanos
end

local function StopGuard()
    if comGuardTarget and commanderID and spGetUnitDefID(commanderID) then
        spGiveOrderToUnit(commanderID, CMD_STOP, {}, {})
    end
    comGuardTarget = nil
end

local function Guard(targetID)
    if comGuardTarget == targetID then return end
    spGiveOrderToUnit(commanderID, CMD_GUARD, {targetID}, {})
    comGuardTarget = targetID
    if DEBUG then Spring.Echo("[MC] commander guards " .. tostring(targetID)) end
end

-- ── Blueprint start ───────────────────────────────────────────────────────────

local function StartBuildOrder()
    local cx, _, cz = spGetUnitPosition(commanderID)
    if not cx then return end
    baseX = math.floor(cx / 16 + 0.5) * 16 + ANCHOR_OFFSET_X
    baseZ = math.floor(cz / 16 + 0.5) * 16 + ANCHOR_OFFSET_Z
    startPending = true
    if DEBUG then Spring.Echo("[MC] anchor " .. baseX .. "," .. baseZ) end
end

local function BeginBuildOrder()
    distState = BP_PLACER.NewDistributed(BUILD_ORDER, baseX, baseZ, 0)
    BP_PLACER.AddBuilder(distState, commanderID)
    startPending = false
    if DEBUG then
        Spring.Echo("[MC] build order started, " .. #distState.queue .. " items")
    end
end

-- ── Phase logic ───────────────────────────────────────────────────────────────

-- The reclaim step sits right after nano #2 in the build order, but reclaiming
-- the lab before con bot #2 has rolled out would cost us that con entirely.
local function GateLabReclaim(frame)
    if not labReclaimGated then return end
    for i = 1, #distState.queue do
        local item = distState.queue[i]
        if item.act == "reclaim" then
            if conCount >= 2 then
                item.deferUntil  = nil
                labReclaimGated  = false
                if DEBUG then Spring.Echo("[MC] lab reclaim released") end
            else
                item.deferUntil = frame + 300
            end
            return
        end
    end
    labReclaimGated = false   -- no reclaim step in this blueprint
end

local function UpdateCommanderPhase(frame, resources)
    if not commanderID or not spGetUnitDefID(commanderID) then
        commanderID = nil
        return
    end

    -- Whatever we were guarding is gone (con died, lab reclaimed) — GUARD has
    -- already self-terminated, so take the commander back.
    if comGuardTarget and not spGetUnitDefID(comGuardTarget) then
        comGuardTarget = nil
        BP_PLACER.AddBuilder(distState, commanderID)
    end

    if not nanoAssistDone then
        if BP_PLACER.CountBuilt(distState, "nano") >= NANO_ASSIST_NUM then
            nanoAssistDone = true
            StopGuard()
            BP_PLACER.AddBuilder(distState, commanderID)
            if DEBUG then Spring.Echo("[MC] nano assist done, commander rejoins pool") end
        elseif conBot1ID and spGetUnitDefID(conBot1ID) then
            local claim = BP_PLACER.GetClaim(distState, conBot1ID)
            -- Only hand over between items, so the commander never abandons a
            -- frame that has no nano in range to finish it.
            if claim and claim.cls == "nano"
               and BP_PLACER.GetClaim(distState, commanderID) == nil then
                BP_PLACER.RemoveBuilder(distState, commanderID)
                Guard(conBot1ID)
            end
            return
        end
    end

    if comGuardTarget == conBot1ID and comGuardTarget ~= nil then return end

    -- Nothing the commander can build right now (typically the next item is a
    -- nano): assist the lab so the next con bot comes out sooner.
    local hasWork = BP_PLACER.GetClaim(distState, commanderID) ~= nil
                 or BP_PLACER.HasClaimable(distState, commanderID, frame, resources)
    if hasWork then
        if comGuardTarget == botLabID and comGuardTarget ~= nil then
            StopGuard()
            BP_PLACER.AddBuilder(distState, commanderID)
        end
    elseif botLabID and spGetUnitDefID(botLabID) and comGuardTarget == nil then
        BP_PLACER.RemoveBuilder(distState, commanderID)
        Guard(botLabID)
    end
end

-- ── Grid expansion (starts once the air lab is up) ──────────────────────────

local TryExpand         -- forward declaration
local TryAssignUpgrades -- ditto: the grid onComplete closure below calls it, and a
                        -- local declared later would resolve to a nil global there

local function AnchorKey(ax, az) return tostring(ax) .. "," .. tostring(az) end

local function AddCompletedAnchor(ax, az)
    local key = AnchorKey(ax, az)
    if not completedKeys[key] then
        completedKeys[key] = true
        completedAnchors[#completedAnchors + 1] = {anchorX = ax, anchorZ = az}
    end
end

local function QueueAirCon()
    if airLabID and spGetUnitDefID(airLabID) and airConDefID then
        spGiveOrderToUnit(airLabID, -airConDefID, {0}, {})
    end
end

local function TryAssignGrids()
    while #freeAirCons > 0 and #pendingGrids > 0 do
        local conID = table.remove(freeAirCons, 1)
        if spGetUnitDefID(conID) then
            spGiveOrderToUnit(conID, CMD_STOP, {}, {})
            local g  = table.remove(pendingGrids, 1)
            gridRotation[AnchorKey(g.anchorX, g.anchorZ)] = g.rotation
            local st = BP_PLACER.New(MEX_GRID_BP, conID, g.anchorX, g.anchorZ,
                                     g.rotation, BP_PLACER.GRID_INTERRUPTS)
            -- The grid's own factory is the last thing built, unless metal is piling
            -- up unspent -- that is what the "float" interrupt is for.
            st.deferFactories  = true
            st.handoffProgress = GRID_HANDOFF
            st.onNanoThreshold = function(gs)
                AddCompletedAnchor(gs.anchorX, gs.anchorZ)
                TryExpand()
            end
            -- 70% built is enough to start retrofitting: the grid's nanos are up by
            -- then, and its own con is off finishing the last few outlying items.
            -- Waiting for `done` meant one grid in a whole game qualified.
            st.onMostlyDone = function(gs)
                local key = AnchorKey(gs.anchorX, gs.anchorZ)
                if not gridFinished[key] then
                    gridFinished[key] = true
                    Spring.Echo(string.format(
                        "[MC] grid (%d, %d) mostly built -- retrofit eligible",
                        gs.anchorX, gs.anchorZ))
                    TryAssignUpgrades()
                end
            end
            st.onComplete = function(gs)
                AddCompletedAnchor(gs.anchorX, gs.anchorZ)
                gridFinished[AnchorKey(gs.anchorX, gs.anchorZ)] = true
                local skipped = 0
                for _, it in ipairs(gs.queue) do
                    if it.status == "skipped" then skipped = skipped + 1 end
                end
                Spring.Echo(string.format(
                    "[MC] grid (%d, %d) finished: %d items, %d skipped -- retrofit eligible",
                    gs.anchorX, gs.anchorZ, #gs.queue, skipped))
                TryExpand()
                TryAssignUpgrades()
            end
            gridStates[#gridStates + 1] = st
            if DEBUG then
                Spring.Echo(string.format("[MC] grid assigned to con %d at (%d, %d)",
                    conID, g.anchorX, g.anchorZ))
            end
        end
    end
end

TryExpand = function()
    if not MEX_GRID_BP or #completedAnchors == 0 then return end
    for _, r in ipairs(BP_PLACER.FindAllValidPlacements(MEX_GRID_BP, completedAnchors)) do
        local key = AnchorKey(r.anchorX, r.anchorZ)
        if not assignedAnchors[key] then
            assignedAnchors[key] = true
            pendingGrids[#pendingGrids + 1] = r
            QueueAirCon()
        end
    end
    TryAssignGrids()
end

-- Seed the first ring of grids around the opening cluster.
local function StartGridExpansion()
    airConDefID = FindAirConDefID(spGetUnitDefID(airLabID))
    if not airConDefID then
        Spring.Echo("[MC] air lab has no air constructor to build")
        return
    end
    -- The opening cluster owns the middle cell; never try to grid over it.
    assignedAnchors[AnchorKey(baseX, baseZ)] = true
    AddCompletedAnchor(baseX, baseZ)

    local dirs = {
        { GRID_SPACING, 0}, {-GRID_SPACING, 0},
        {0,  GRID_SPACING}, {0, -GRID_SPACING},
    }
    for _, d in ipairs(dirs) do
        local ax, az = baseX + d[1], baseZ + d[2]
        assignedAnchors[AnchorKey(ax, az)] = true
        -- Face the opening cluster, so this grid's first nano is inside the reach of
        -- the nanos already standing there and goes up in seconds.
        local rot = BP_PLACER.BestRotation(MEX_GRID_BP, ax, az, baseX, baseZ)
        pendingGrids[#pendingGrids + 1] = {anchorX = ax, anchorZ = az, rotation = rot}
        QueueAirCon()
    end
    if DEBUG then Spring.Echo("[MC] grid expansion started, " .. #pendingGrids .. " cells") end
    TryAssignGrids()
end

-- ── Retrofit (T2 upgrade of a finished grid) ─────────────────────────────────

-- A T2 con is one that can build what the upgrade blueprint asks for.  Asking the
-- unit defs beats hard-coding "coraca": it is the same question the placer will
-- ask when it tries to claim an item.
local function IsT2Con(defID)
    if not (UPGRADE_BP and UPGRADE_BP.layout and UPGRADE_BP.layout[1]) then return false end
    local ud = UnitDefNames[UPGRADE_BP.layout[1].n]
    return ud and BP_PLACER.CanBuild(defID, ud.id) or false
end

TryAssignUpgrades = function()
    if not UPGRADE_BP then return end
    while #freeT2Cons > 0 do
        local conID = freeT2Cons[1]
        if not spGetUnitDefID(conID) then
            table.remove(freeT2Cons, 1)
        else
            -- Nearest finished grid that has not been retrofitted yet.
            local cx, _, cz = spGetUnitPosition(conID)
            local best, bestD2, bestKey = nil, math.huge, nil
            for _, a in ipairs(completedAnchors) do
                local key = AnchorKey(a.anchorX, a.anchorZ)
                -- Only grids that finished their own blueprint: a grid still
                -- building would be competing with its own retrofit for metal.
                if gridFinished[key] and not upgradedKeys[key]
                   and key ~= AnchorKey(baseX, baseZ) then
                    local dx, dz = (cx or 0) - a.anchorX, (cz or 0) - a.anchorZ
                    local d2 = dx * dx + dz * dz
                    if d2 < bestD2 then best, bestD2, bestKey = a, d2, key end
                end
            end
            if not best then return end          -- nothing ripe; keep the con waiting
            table.remove(freeT2Cons, 1)
            upgradedKeys[bestKey] = true
            spGiveOrderToUnit(conID, CMD_STOP, {}, {})
            local st = BP_PLACER.New(UPGRADE_BP, conID, best.anchorX, best.anchorZ,
                                     gridRotation[bestKey] or 0,
                                     BP_PLACER.GRID_INTERRUPTS)
            st.clearBlockers   = true    -- reclaim the mex/winds the fusions need
            st.handoffProgress = GRID_HANDOFF
            -- Hand the con straight to the next grid instead of retiring it.
            st.onComplete = function(us)
                if us.builderID and spGetUnitDefID(us.builderID) then
                    freeT2Cons[#freeT2Cons + 1] = us.builderID
                    TryAssignUpgrades()
                end
            end
            upgradeStates[#upgradeStates + 1] = st
            Spring.Echo(string.format("[MC] retrofit started at (%d, %d) by con %d",
                best.anchorX, best.anchorZ, conID))
        end
    end
end

-- ── Hand-off ─────────────────────────────────────────────────────────────────

-- Metal is banking: the build order cannot spend what the economy earns any more.
-- Put an air lab up inside the nanos' reach and let the grid system take over.
local function StartHandoff()
    handoffStarted = true
    airLabDefID = FindAirFactoryDefID()
    if not airLabDefID then
        Spring.Echo("[MC] hand-off: no builder we own can place an air factory")
        return
    end
    local x, z, nanos = FindAirLabSpot()
    if not x then
        Spring.Echo("[MC] hand-off: nowhere to put the air lab")
        handoffStarted = false
        return
    end
    local name = UnitDefs[airLabDefID] and UnitDefs[airLabDefID].name
    local item = BP_PLACER.InsertPriorityItem(distState, name, x, z, 0)
    if not item then
        Spring.Echo("[MC] hand-off: could not queue " .. tostring(name))
        handoffStarted = false
        return
    end
    airLabItem  = item
    airLabFrame = currentFrame
    -- Not DEBUG-gated: this is the one event that decides whether the bot scales,
    -- and a silent success is indistinguishable from a silent failure.
    Spring.Echo(string.format(
        "[MC] HAND-OFF frame=%d: %s at (%d, %d), %d nanos in range, %d builders",
        currentFrame, tostring(name), x, z, nanos or 0, #distState.builders))
end

-- ── Nano army/eco balance ────────────────────────────────────────────────────

local function IsNanoTurret(defID)
    local d = defID and UnitDefs[defID]
    if not d then return false end
    if not (d.isBuilder and not d.isFactory and not d.canFly) then return false end
    return d.speed == nil or d.speed == 0
end

-- What this builder is actually pouring build power into right now.
local function NanoTarget(uid)
    local t = Spring.GetUnitIsBuilding and Spring.GetUnitIsBuilding(uid)
    if t then return t end
    local cmds = spGetUnitCommands(uid, 1)
    local c = cmds and cmds[1]
    if c and (c.id == CMD_REPAIR or c.id == CMD_GUARD) and c.params then
        return c.params[1]
    end
    return nil
end

-- Army spending is anything whose output is a unit: a factory, or a mobile unit
-- under construction.  Everything else -- mex, wind, nano, fusion -- is eco.
local function SpendClass(targetID)
    if not targetID then return nil end
    local d = UnitDefs[spGetUnitDefID(targetID) or -1]
    if not d then return nil end
    if d.isFactory then return "army" end
    if d.speed and d.speed > 0 then return "army" end
    return "eco"
end

local function NanoBuildSpeed(defID)
    local d = UnitDefs[defID]
    return (d and d.buildSpeed) or 0
end

-- The nearest factory this nano can physically reach; nil if none.
local function FactoryInReach(uid, defID)
    local reach = (UnitDefs[defID] and UnitDefs[defID].buildDistance) or 380
    local ux, _, uz = spGetUnitPosition(uid)
    if not ux then return nil end
    local best, bestD2 = nil, reach * reach
    for fid in pairs(factories) do
        if spGetUnitDefID(fid) then
            local fx, _, fz = spGetUnitPosition(fid)
            if fx then
                local dx, dz = ux - fx, uz - fz
                local d2 = dx * dx + dz * dz
                if d2 <= bestD2 then best, bestD2 = fid, d2 end
            end
        else
            factories[fid] = nil
        end
    end
    return best
end

local function UpdateNanoBalance(frame)
    -- Headroom: near the unit cap, army is the only thing worth spending on.
    local target = ARMY_SHARE
    local maxUnits = Spring.GetTeamMaxUnits and Spring.GetTeamMaxUnits(myTeamID)
    local count    = Spring.GetTeamUnitCount and Spring.GetTeamUnitCount(myTeamID)
    if maxUnits and count and (maxUnits - count) <= ARMY_CAP_SLACK then
        target = 1.0
    end

    local armyBP, ecoBP = 0, 0
    local spentArmy, spentEco = 0, 0     -- measured, for reporting
    local ecoPool = {}                   -- nanos available to switch to army
    for _, uid in ipairs(spGetTeamUnits(myTeamID) or {}) do
        local dID = spGetUnitDefID(uid)
        if IsNanoTurret(dID) and not Spring.GetUnitIsBeingBuilt(uid) then
            local bp = NanoBuildSpeed(dID)
            local cls = SpendClass(NanoTarget(uid))
            if cls == "army" then spentArmy = spentArmy + bp
            elseif cls == "eco" then spentEco = spentEco + bp end

            if armyNanos[uid] and spGetUnitDefID(armyNanos[uid]) then
                armyBP = armyBP + bp
            else
                armyNanos[uid] = nil
                ecoBP = ecoBP + bp
                ecoPool[#ecoPool + 1] = {uid = uid, defID = dID, bp = bp}
            end
        end
    end

    local totalBP = armyBP + ecoBP
    if totalBP <= 0 then return end
    local wantBP = target * totalBP
    local moves  = 0

    -- Build power comes in whole nanos, so the exact target is usually unreachable.
    -- Move a nano only when doing so gets us CLOSER to the target than staying put:
    -- comparing shares against a dead band instead made a single nano flip between
    -- 0% and 100% every tick, since neither value is ever within 5% of 30%.
    local function improves(newBP)
        return math.abs(newBP - wantBP) < math.abs(armyBP - wantBP)
    end

    if armyBP < wantBP then
        for _, n in ipairs(ecoPool) do
            if moves >= NANO_MOVES_MAX or not improves(armyBP + n.bp) then break end
            local fid = FactoryInReach(n.uid, n.defID)
            if fid then
                spGiveOrderToUnit(n.uid, CMD_GUARD, {fid}, {})
                armyNanos[n.uid] = fid
                armyBP = armyBP + n.bp
                moves  = moves + 1
            end
        end
    elseif armyBP > wantBP then
        for uid, fid in pairs(armyNanos) do
            if moves >= NANO_MOVES_MAX then break end
            local dID = spGetUnitDefID(uid)
            if dID then
                local bp = NanoBuildSpeed(dID)
                if not improves(armyBP - bp) then break end
                -- Released nanos fall back to assisting whatever is being built
                -- nearby, which is eco work.
                spGiveOrderToUnit(uid, CMD_STOP, {}, {})
                armyNanos[uid] = nil
                armyBP = armyBP - bp
                moves  = moves + 1
            else
                armyNanos[uid] = nil
            end
        end
    end
    local share = armyBP / totalBP

    if DEBUG then
        local spent = spentArmy + spentEco
        local msg = string.format("[MC] nano bp: allocated army %.0f%% (target %.0f%%), "
            .. "actually spending army %.0f%% of %.0f bp, %d factories",
            share * 100, target * 100,
            spent > 0 and (spentArmy / spent * 100) or 0, spent, (function()
                local n = 0; for _ in pairs(factories) do n = n + 1 end; return n end)())
        if msg ~= lastArmyLog then Spring.Echo(msg); lastArmyLog = msg end
    end
end

-- ── Widget callbacks ──────────────────────────────────────────────────────────

function widget:Initialize()
    local ok1, r1 = pcall(VFS.Include, "LuaUI/Widgets/blueprint_placer.lua")
    local ok2, r2 = pcall(VFS.Include,
        "LuaUI/Widgets/blueprints/general/build_order_blueprint.lua")
    if not ok1 then Spring.Echo("[MC] ERROR loading blueprint_placer: "      .. tostring(r1)); return end
    if not ok2 then Spring.Echo("[MC] ERROR loading build_order_blueprint: " .. tostring(r2)); return end
    local ok3, r3 = pcall(VFS.Include,
        "LuaUI/Widgets/blueprints/general/mex_grid_alab.lua")
    if not ok3 then Spring.Echo("[MC] ERROR loading mex_grid_alab: " .. tostring(r3)); return end
    local ok4, r4 = pcall(VFS.Include, "LuaUI/Widgets/blueprints/general/upgrade.lua")
    if ok4 then UPGRADE_BP = r4
    else Spring.Echo("[MC] no upgrade blueprint (" .. tostring(r4) .. "); retrofits disabled") end
    BP_PLACER    = r1
    BUILD_ORDER  = r2
    MEX_GRID_BP  = r3
    GRID_SPACING = BP_PLACER.GRID_SPACING

    if DEBUG then
        -- Real footprints, to check them against the sizes blueprint_gen assumed.
        for _, n in ipairs({"corwin", "cormex", "cornanotc", "corlab", "corck"}) do
            local ud = UnitDefNames[n]
            if ud then
                Spring.Echo(string.format("[MC] def %s xsize=%s zsize=%s buildDist=%s",
                    n, tostring(ud.xsize), tostring(ud.zsize), tostring(ud.buildDistance)))
            end
        end
    end

    myTeamID = spGetMyTeamID()
    for _, uid in ipairs(Spring.GetTeamUnits(myTeamID) or {}) do
        if IsCommander(spGetUnitDefID(uid)) then
            commanderID = uid
            break
        end
    end
    if commanderID then StartBuildOrder() end
end

function widget:UnitCreated(unitID, unitDefID, teamID, builderID)
    if not myTeamID then myTeamID = spGetMyTeamID() end
    if teamID ~= myTeamID then return end

    -- Must come first: the corlab is itself a queue item, and so is anything
    -- else that would hit an early return below.
    if distState then
        BP_PLACER.OnUnitCreated(distState, unitID, unitDefID, builderID)
    end

    local d = UnitDefs[unitDefID]
    if not d then return end

    if d.isFactory then
        if airLabDefID and unitDefID == airLabDefID and not airLabID then
            airLabID = unitID
            if DEBUG then Spring.Echo("[MC] air lab frame " .. unitID) end
        elseif not botLabID then
            botLabID = unitID
            if DEBUG then Spring.Echo("[MC] bot lab " .. unitID) end
        end
        return
    end

    -- Con bots start life inside the lab; they are only usable once finished.
    if builderID and builderID == botLabID and IsGroundCon(d) then
        pendingCons[unitID] = true
    end
end

function widget:UnitFinished(unitID, unitDefID, teamID)
    if teamID ~= myTeamID then return end
    local d = UnitDefs[unitDefID]

    if IsCommander(unitDefID) and not commanderID then
        commanderID = unitID
        StartBuildOrder()
    end

    -- Lab done → queue con bot #1.  Con #2 is queued CON_GAP_FRAMES after #1
    -- finishes, which is the spacing the sim's build order assumes.
    if unitID == botLabID then
        conDefID = FindConBotDefID(unitDefID)
        if conDefID then spGiveOrderToUnit(botLabID, -conDefID, {0}, {}) end
        if DEBUG then Spring.Echo("[MC] lab finished, con #1 queued") end
    end

    if d and d.isFactory then
        factories[unitID] = true
        -- An advanced air lab can make the T2 con that does retrofits.
        if UPGRADE_BP and unitID ~= airLabID then
            local t2 = FindAirConDefID(unitDefID)
            if t2 and IsT2Con(t2) then
                for _ = 1, UPGRADE_CONS_PER_LAB do
                    spGiveOrderToUnit(unitID, -t2, {0}, {})
                end
            end
        end
    end

    -- Air lab finished -> the grid system takes over from here.
    if unitID == airLabID then
        StartGridExpansion()
    end

    -- Air cons roll out.  The factory gives them a guard order on itself as they
    -- leave, which arrives AFTER this callback -- so stopping only here leaves them
    -- assisting the lab forever, permanently "busy", and they never take a grid.
    -- Stop now and again once that order has landed.
    if airLabID and d and d.isBuilder and d.canFly and not d.isFactory then
        spGiveOrderToUnit(unitID, CMD_STOP, {}, {})
        pendingStops[#pendingStops + 1] = {unitID = unitID, fireFrame = currentFrame + 30}
        if IsT2Con(unitDefID) then
            freeT2Cons[#freeT2Cons + 1] = unitID
            TryAssignUpgrades()
        else
            freeAirCons[#freeAirCons + 1] = unitID
            TryAssignGrids()
        end
    end

    if pendingCons[unitID] then
        pendingCons[unitID] = nil
        conCount = conCount + 1
        if not conBot1ID then
            conBot1ID = unitID
            con2Frame = currentFrame + CON_GAP_FRAMES
        end
        BP_PLACER.AddBuilder(distState, unitID)
        if DEBUG then Spring.Echo("[MC] con #" .. conCount .. " joined (" .. unitID .. ")") end
    end

    local x, _, z = spGetUnitPosition(unitID)
    if distState then
        BP_PLACER.OnUnitFinished(distState, unitID, unitDefID, x, z)
    end
    for _, gs in ipairs(gridStates) do
        if not gs.done then
            BP_PLACER.OnUnitFinished(gs, unitID, unitDefID, x, z)
        end
    end
    for _, us in ipairs(upgradeStates) do
        if not us.done then
            BP_PLACER.OnUnitFinished(us, unitID, unitDefID, x, z)
        end
    end
end

-- Fires when a finished unit actually leaves the factory: the last moment the
-- engine's auto-guard can be applied, so clear it here too.
function widget:UnitFromFactory(unitID, unitDefID, teamID, factID)
    if teamID ~= myTeamID then return end
    if factID and factID == airLabID then
        spGiveOrderToUnit(unitID, CMD_STOP, {}, {})
    end
end

function widget:UnitDestroyed(unitID, unitDefID, teamID)
    if teamID ~= myTeamID then return end
    if DEBUG then
        local x, _, z = spGetUnitPosition(unitID)
        Spring.Echo(string.format("[MC] lost %s id=%s at (%s,%s) f=%d beingBuilt=%s",
            UnitDefs[unitDefID] and UnitDefs[unitDefID].name or "?", tostring(unitID),
            tostring(x and math.floor(x)), tostring(z and math.floor(z)),
            currentFrame, tostring(Spring.GetUnitIsBeingBuilt(unitID))))
    end
    if distState then BP_PLACER.OnUnitDestroyed(distState, unitID) end
    pendingCons[unitID] = nil
    factories[unitID]   = nil
    armyNanos[unitID]   = nil
    if unitID == commanderID then commanderID = nil end
    if unitID == conBot1ID   then conBot1ID   = nil end
    if unitID == botLabID    then botLabID    = nil end
    if unitID == comGuardTarget then comGuardTarget = nil end
end

function widget:GameFrame(frame)
    currentFrame = frame
    if not myTeamID or not BP_PLACER then return end

    if startPending and frame >= START_FRAME then BeginBuildOrder() end
    if not distState then return end

    -- Con bot #2, one CON_GAP after con #1 finished.
    if not con2Queued and con2Frame and frame >= con2Frame then
        if botLabID and spGetUnitDefID(botLabID) and conDefID then
            spGiveOrderToUnit(botLabID, -conDefID, {0}, {})
            con2Queued = true
            if DEBUG then Spring.Echo("[MC] con #2 queued at frame " .. frame) end
        elseif not botLabID then
            con2Queued = true   -- lab gone; nothing to queue from
        end
    end

    local si = 1
    while si <= #pendingStops do
        local ps = pendingStops[si]
        if frame >= ps.fireFrame then
            if spGetUnitDefID(ps.unitID) then
                spGiveOrderToUnit(ps.unitID, CMD_STOP, {}, {})
            end
            table.remove(pendingStops, si)
        else
            si = si + 1
        end
    end

    if frame % 10 ~= 0 then return end

    local _, m,  ms,  _, mi = pcall(Spring.GetTeamResources, myTeamID, "metal")
    local _, em, ems        = pcall(Spring.GetTeamResources, myTeamID, "energy")
    local resources = {
        metal  = m  or 0, metalStorage  = ms  or 1000,
        energy = em or 0, energyStorage = ems or 1000,
        metalIncome = mi or 0,
    }

    -- Hand-off trigger: metal banked above BANK_FRAC of storage for BANK_HOLD frames,
    -- but only once the economy is real (see the guards above).
    if not handoffStarted and resources.metalStorage > 0
       and resources.metalIncome >= HANDOFF_MIN_INCOME then
        if (resources.metal / resources.metalStorage) >= BANK_FRAC then
            bankFrames = bankFrames + 10
            if bankFrames >= BANK_HOLD then StartHandoff() end
        else
            bankFrames = 0
        end
    end

    -- Watchdog: the lab is queued but nothing has begun building it.  Silence here
    -- used to mean a def no builder could place; say so rather than stalling mutely.
    if airLabItem and not airLabID and airLabFrame and (frame - airLabFrame) > 900 then
        local st = airLabItem.status
        if st == "skipped" or st == "pending" then
            -- The spot was taken (usually by the build order itself).  Try again
            -- somewhere else: without this lab there is no army and no expansion,
            -- so giving up once is giving up for the whole game.
            airLabRetries = (airLabRetries or 0) + 1
            Spring.Echo(string.format(
                "[MC] hand-off retry %d: %s not started (status=%s), picking a new spot",
                airLabRetries, tostring(airLabItem.n), tostring(st)))
            airLabItem.status = "skipped"
            airLabItem.built  = true          -- take the dead entry out of the queue
            airLabItem = nil
            if airLabRetries <= 5 then
                handoffStarted = false        -- StartHandoff runs again next tick
                bankFrames     = BANK_HOLD    -- and fires immediately
            elseif not airLabWarned then
                airLabWarned = true
                Spring.Echo("[MC] hand-off GAVE UP after 5 attempts")
            end
        end
    end

    -- Drive every grid, and prune the finished ones.
    local gi = 1
    while gi <= #gridStates do
        local gs = gridStates[gi]
        if gs.done then table.remove(gridStates, gi)
        else
            BP_PLACER.Update(gs, frame, resources)
            gi = gi + 1
        end
    end
    if #freeAirCons > 0 and #pendingGrids > 0 then TryAssignGrids() end

    -- Retrofits yield to everything else when metal is short: a T2 mex earns less
    -- per metal spent than a T1 one, so a retrofit competing with a normal grid
    -- during a stall is strictly bad. Stop the builders rather than just pausing,
    -- or they sit holding a half-issued order.
    local mFrac = resources.metalStorage > 0
                  and (resources.metal / resources.metalStorage) or 1
    if not retrofitPaused and mFrac < RETROFIT_STALL_FRAC then
        retrofitPaused = true
        for _, us in ipairs(upgradeStates) do
            if us.builderID and spGetUnitDefID(us.builderID) then
                spGiveOrderToUnit(us.builderID, CMD_STOP, {}, {})
                us.currentTask = nil
            end
        end
        if DEBUG then Spring.Echo("[MC] retrofits paused (metal stall)") end
    elseif retrofitPaused and mFrac > RETROFIT_RESUME_FRAC then
        retrofitPaused = false
        if DEBUG then Spring.Echo("[MC] retrofits resumed") end
    end

    if not retrofitPaused then
        local ui = 1
        while ui <= #upgradeStates do
            local us = upgradeStates[ui]
            if us.done then table.remove(upgradeStates, ui)
            else
                BP_PLACER.Update(us, frame, resources)
                ui = ui + 1
            end
        end
    end
    if #freeT2Cons > 0 then TryAssignUpgrades() end

    if frame % NANO_REBALANCE == 0 then UpdateNanoBalance(frame) end

    GateLabReclaim(frame)
    -- Phases first: the commander must be out of the builder pool before
    -- Update hands it a claim it is about to abandon.
    UpdateCommanderPhase(frame, resources)

    if not distState.done then
        BP_PLACER.Update(distState, frame, resources)
    end
end
