-- Blueprint: bad_com_start
-- Generated by blueprint_editor.html
-- Grid: 15×15 cells, center at cell (7,7), 1 cell = 16 world units
local M = {}
M.layout = {
    {n="cormex", x=  -32, z=   96, f=0},
    {n="cormex", x=  -32, z=   32, f=0},
    {n="corwin", x=  -88, z=  104, f=0},
    {n="corwin", x=  -88, z=   56, f=0},
    {n="corlab", x=   48, z=   80, f=1},
    {n="corwin", x=  -88, z=    8, f=0},
    {n="corwin", x=  -88, z=  -40, f=0},
    {n="corwin", x=  -88, z=  -88, f=0},
    {n="cornanotc", x=  104, z=    8, f=0},
    {n="cormex", x=  -32, z=  -32, f=0},
    {n="corwin", x=  -40, z=  -88, f=0},
    {n="corwin", x=   56, z=  -88, f=0},
    {n="corwin", x=  104, z=  -88, f=0},
    {n="corrad", x=   96, z=  -40, f=0},
}
return M
