-- Blueprint: con_bot_grid
-- Generated by blueprint_editor.html
-- Grid: 15×15 cells, center at cell (7,7), 1 cell = 16 world units
local M = {}
M.layout = {
    {n="cornanotc", x=  -88, z=  104, f=0},
    {n="corwin", x=  -88, z=    8, f=0},
    {n="corwin", x=  -88, z=  -40, f=0},
    {n="corwin", x=  -88, z=  -88, f=0},
    {n="cormex", x=  -32, z=  -16, f=0},
    {n="cormex", x=  -32, z=  -80, f=0},
    {n="cormex", x=   48, z=  -80, f=0},
    {n="cormex", x=   48, z=  -16, f=0},
    {n="corwin", x=  104, z=  -88, f=0},
    {n="corwin", x=  104, z=  -40, f=0},
    {n="corwin", x=  104, z=    8, f=0},
    {n="cornanotc", x=  104, z=  104, f=0},
}
return M
