-- Blueprint: empty_grid
-- Generated by blueprint_editor.html
-- Grid: 30×30 cells, center at cell (15,15), 1 cell = 16 world units
local M = {}
M.layout = {
    {n="cornanotc", x=  216, z=  216, f=0},
    {n="cornanotc", x=   24, z=  216, f=0},
    {n="cornanotc", x=  -24, z=  216, f=0},
    {n="cornanotc", x= -216, z=  216, f=0},
    {n="cornanotc", x= -216, z=   24, f=0},
    {n="cornanotc", x= -216, z=  -24, f=0},
    {n="cornanotc", x= -216, z= -216, f=0},
    {n="cornanotc", x=  -24, z= -216, f=0},
    {n="cornanotc", x=   24, z= -216, f=0},
    {n="cornanotc", x=  216, z= -216, f=0},
    {n="cornanotc", x=  216, z=  -24, f=0},
    {n="cornanotc", x=  216, z=   24, f=0},
}
return M
