-- Blueprint: line_com
-- Generated by blueprint_editor.html
-- Grid: 40×40 cells, center at cell (20,20), 1 cell = 16 world units
local M = {}
M.layout = {
    {n="cormex", x= -128, z=  -16, f=0},
    {n="cormex", x=  -64, z=  -16, f=0},
    {n="corwin", x=  -56, z=  -72, f=0},
    {n="corwin", x= -104, z=  -72, f=0},
    {n="corlab", x=   64, z=   64, f=0},
    {n="corwin", x=  -56, z=   40, f=0},
    {n="corwin", x= -104, z=   40, f=0},
    {n="corwin", x=  -56, z=   88, f=0},
    {n="cornanotc", x=  136, z=  -56, f=0},
}
return M
