-- Blueprint: upgrade
-- Generated by blueprint_editor.html
-- Grid: 30×30 cells, center at cell (15,15), 1 cell = 16 world units
local M = {}
M.layout = {
    {n="cormoho", x=  -96, z= -160, f=0},
    {n="cormoho", x=  -32, z= -160, f=0},
    {n="cormoho", x=   32, z= -160, f=0},
    {n="cormoho", x=   96, z= -160, f=0},
    {n="cormoho", x=  160, z=  -96, f=0},
    {n="cormoho", x=  160, z=  -32, f=0},
    {n="corfus", x=  184, z= -184, f=0},
    {n="cormoho", x=  160, z=   32, f=0},
    {n="cormoho", x=  160, z=   96, f=0},
    {n="corfus", x=  184, z=  184, f=0},
    {n="cormoho", x=   96, z=  160, f=0},
    {n="cormoho", x=   32, z=  160, f=0},
    {n="cormoho", x=  -32, z=  160, f=0},
    {n="cormoho", x=  -96, z=  160, f=0},
    {n="corfus", x= -184, z=  184, f=0},
    {n="cormoho", x= -160, z=   96, f=0},
    {n="cormoho", x= -160, z=   32, f=0},
    {n="cormoho", x= -160, z=  -32, f=0},
    {n="cormoho", x= -160, z=  -96, f=0},
    {n="corfus", x= -184, z= -184, f=0},
    {n="cormoho", x=    0, z=   96, f=0},
    {n="cormoho", x=  -96, z=    0, f=0},
}
return M
