-- macro_controller.lua  ─  sim-derived build order, executed distributed (COR)
--
-- The whole economy is one ordered blueprint (blueprints/general/build_order_blueprint.lua,
-- generated by build_order_sim.py + blueprint_gen.py).  blueprint_placer's distributed
-- mode runs it with several builders at once: each idle builder claims the lowest-index
-- item it can build, and leaves a frame at 85% as soon as a finished nano turret can
-- complete it.  That keeps a fresh nanoframe standing at all times, which is what the
-- nanos need to stay busy.
--
-- Hard-coded early game (the rest is emergent):
--   1. The commander is the only builder, so it places wind, wind, corlab, mex, wind, wind.
--   2. The lab's first con bot joins the queue and reaches nano #1 first (the commander
--      cannot build nano turrets).  The commander then GUARDs that con so it assists
--      nanos #1 and #2 instead of running ahead.
--   3. After 2 nanos the commander rejoins the pool.  Con bot #2 is queued 60 s after
--      con #1 finished (the sim's CON_GAP), and the lab is reclaimed once it exists —
--      that refund is part of the build order, not an afterthought.
--
-- HAND-OFF.  The build order is a kick-starter, planned to ~4.5 game-min.  Past that
-- the bot earns faster than it can place, and metal starts banking (measured: surplus
-- at frame ~8100, metal binned from ~9000).  When that happens it puts an air lab up
-- inside the existing nanos' reach -- so it is finished in seconds, not flown to --
-- and from there the grid system takes over: air cons each run a mex_grid_alab
-- blueprint, expanding outward one grid cell at a time.

local widget = widget
local Spring = Spring
local CMD    = CMD

local spGetUnitPosition = Spring.GetUnitPosition
local spGetUnitDefID    = Spring.GetUnitDefID
local spGiveOrderToUnit = Spring.GiveOrderToUnit
local spGetMyTeamID     = Spring.GetMyTeamID
local spGetGroundHeight = Spring.GetGroundHeight
local spGetUnitCommands = Spring.GetUnitCommands
local spGetTeamUnits    = Spring.GetTeamUnits
local spGetFactoryCommands = Spring.GetFactoryCommands

local CMD_GUARD   = (CMD and CMD.GUARD)   or 25
local CMD_REPAIR  = (CMD and CMD.REPAIR)  or 40
local CMD_RECLAIM = (CMD and CMD.RECLAIM) or 90
local CMD_STOP    = 0
local CMD_STOCKPILE = (CMD and CMD.STOCKPILE) or 117

-- Con bot #2 trails #1 by this much; mirrors CON_GAP in build_order_sim.py.
local CON_GAP_FRAMES  = 60 * 30
local NANO_ASSIST_NUM = 2     -- nanos the commander assists the con through
-- The blueprint's first wind sits almost on top of the anchor, and the bot lab sits
-- 64 elmos north of it, so anchoring on the commander means the engine shoves the
-- commander aside before it can build.  Offsetting the blueprint diagonally clears
-- the commander's spawn of both, while keeping every early item inside its build
-- range (~152 elmos to a wind) so it never has to walk to place them.
-- Chosen by checking every offset against the actual layout: this is the one where
-- nothing lands on the commander and 10 of the first 12 items are inside its build
-- range.  Re-check it when the build order is regenerated.
local ANCHOR_OFFSET_X = -96
local ANCHOR_OFFSET_Z = -48

-- Hand-off: metal sitting above this share of storage for this long means the build
-- order can no longer spend what the economy earns.  The guards matter — the game
-- STARTS with storage full and no income at all, so the bank test alone fires at
-- frame 0.  Real banking only counts once the economy is actually running.
-- Banking 2k metal already means energy and build power should have been scaled
-- earlier, so hand over on the first clear sign of surplus rather than a full store.
-- The income test is what rules out the start of the game, where storage is full but
-- nothing is being produced.
local BANK_FRAC          = 0.20
local BANK_HOLD          = 150    -- frames (5 s)
local HANDOFF_MIN_INCOME = 40     -- m/s: proves this is income, not the starting stock
local AIR_LAB_MIN_NANOS = 2   -- nanos that must cover the air lab's spot
-- One air con runs a whole grid, so its travel between sites is the bottleneck.
-- Leave each frame this far along for the grid's nanos to finish, and fly on.
local GRID_HANDOFF      = 0.30
-- Air-con reserve.  A new grid opens the moment a neighbour reaches its nano threshold,
-- but its air con is only queued then, so every grid waited for a con to be built --
-- 32-74 s for the first four (queued together at 3:56, assigned 4:28-5:09), and the
-- growth rate is set by exactly this grid-to-grid latency (lessons_learned, "Scaling").
-- Keeping a couple of cons ready turns that wait into zero for ~110 metal each.
local AIR_CON_RESERVE   = 2

-- CAPSTONE: the one big building a mex grid is crowned with.  The blueprint asks
-- for a T2 air lab; any grid can take something else instead, which is how the
-- bot spends a grid's worth of ground on something other than more air.
--
-- The catch is WHO can build it.  A grid is run by a T1 air con (corca), and that
-- con can only place the T2 air lab -- a nuke needs a T2 con (coraca), a T2 bot
-- lab needs a con bot (corck), and nothing we own can place a T2 vehicle plant.
-- So a capstone the grid's own con cannot build is taken out of the grid's queue
-- and handed to a builder that can, rather than being retried forever.
local CAPSTONE_DEFAULT = "coraap"    -- T2 air lab, as the blueprint has it
local CAPSTONE_PLAN = {
    -- grid number (order assigned) -> what to crown it with
    [4] = "corsilo",                 -- nuke, to exercise the hand-off path
}

-- Retrofit: a finished mex grid is upgraded in place to T2 mexes + fusions by a
-- T2 air con.  The grid's own nanos assist, so build power that would otherwise
-- idle in a finished grid goes back to work, and T2 mexes raise income per unit
-- -- which matters once the unit cap, not metal, is the ceiling.
local UPGRADE_CONS_PER_LAB = 2     -- T2 air cons each advanced air lab builds
-- T2 mexes are LESS metal-efficient than T1, so a retrofit must never compete
-- with a normal grid for metal: while stalling, retrofit builders are stopped.
local RETROFIT_STALL_FRAC  = 0.15  -- stalling below this share of metal storage
local RETROFIT_RESUME_FRAC = 0.30  -- resume once comfortably above it

-- Wind consolidation.  A wind is 25 e/s for one unit slot; four of them in a 2x2
-- block can be replaced by ONE fusion (850 e/s) or one T2 mex (4x a T1 mex), so
-- once the unit cap is the binding constraint the swap is worth ~34x the energy
-- per slot.  Grid wind rows sit 48 elmos apart both inside a grid (216, 168, ...)
-- and ACROSS a grid boundary (216 vs 480-216 = 264), so the whole base is one
-- continuous 48-elmo lattice: the blocks are found centrally here rather than by
-- any one grid, which is what makes the ones straddling two grids anybody's job.
-- Headroom at which the cap counts as "tight".  Must be relative as well as
-- absolute: the DEFAULT cap is 2000, so a flat 2000 would read as tight from the
-- first frame of every game, and even 1000 is half of it.  Games here may be run
-- at 5000.
local CONSOLIDATE_SLACK  = 1000  -- absolute headroom...
local CAP_SLACK_FRAC     = 0.20  -- ...but never more than this share of the cap
local WIND_LATTICE       = 48    -- elmos between adjacent winds
local CONSOLIDATE_SCAN   = 300   -- frames between scans; one scan finds EVERY block,
                                 -- so jobs start every tick from the cached list
local CONSOLIDATE_MAX    = 60    -- blocks tracked at once, to bound the scan's cost

-- Wind reclaim is a plain nano task, not something idle builders drift into: one
-- air con is a few hundred build power against a base full of nanos, and an idle
-- nano near a half-reclaimed wind will happily REPAIR it back up, which is why
-- the old version crawled.  Every nano that can reach a condemned wind is put on
-- it, so none is left to fight over it.
local RECLAIM_TRIGGER_FRAC = 0.20  -- start when unit-cap headroom drops to this share
local RECLAIM_BUDGET_FRAC  = 0.02  -- winds condemned at once, as a share of the cap:
                                   -- enough to free real space, small enough that the
                                   -- energy loss is not a cliff
local RECLAIM_EVERY        = 90    -- frames between passes

-- Spend pressure.  Metal sitting in the bank is build power that was not used,
-- and the interrupts only react once a resource is nearly out -- so the bank
-- hovers at whatever the interrupt thresholds imply.  Rather than react to the
-- bank, watch PULL against INCOME: pull is what the builders are asking for, so
-- income above pull means we are under-spending and will bank, seconds before it
-- shows up in storage.  The response is to open more frames at once by handing
-- them to the nanos sooner.
local SPEND_FAST     = 0.15   -- handoff when under-spending: place more, finish less
local SPEND_SLOW     = 0.60   -- handoff when short: finish what is already started
local BANK_HIGH      = 0.25   -- stored metal share that counts as banking
local BANK_LOW       = 0.08   -- ...and as running dry
local START_FRAME     = 15    -- orders issued at frame 0 are dropped by the engine

-- Nano build power is split between two jobs: assisting a factory (its output is
-- units, so that is ARMY spending) and building structures (ECO spending).  Nanos
-- are the bulk of the build power, so this split is what actually decides how much
-- army the bot makes.
local ARMY_SHARE      = 0.30   -- target share of nano build power spent on army
local ARMY_CAP_SLACK  = 1000   -- unit headroom below this -> everything to army
                               -- (also clamped by CAP_SLACK_FRAC, see CapSlack)
local NANO_REBALANCE  = 30     -- frames between rebalances
local NANO_MOVES_MAX  = 4      -- nanos reassigned per rebalance, to avoid thrash

-- Energy look-ahead for the grids.  blueprint_placer's energy interrupt fires once stored
-- energy is under 17% of storage.  With a ~6k energy storage up by ~3:30 that is too late:
-- every grid opens with 12 nano turrets before its first wind, four grids start within a
-- minute, pull outruns income, the storage hides it, and when the interrupt finally fires
-- the winds cannot catch up.  Measured in four mirror runs: energy-stalled 60-90% of
-- 5:00-6:00 while 1.4-2.3k metal sat banked.  So the grids' energy check looks ahead: it
-- fires when stored energy is PROJECTED to cross the same threshold within
-- ENERGY_LOOKAHEAD seconds at the current (smoothed) net drain.
local ENERGY_LOOKAHEAD = 30     -- seconds
local ENERGY_LOW       = 0.17   -- the placer's own threshold (ENERGY_LOW_FRAC)
local NET_SMOOTH       = 0.1    -- EMA weight per 10-frame resource read (~3 s)
local GridInterrupts            -- defined next to ReadResources

function widget:GetInfo()
    return {
        name    = "Macro Controller",
        desc    = "Distributed sim build order (COR)",
        author  = "",
        date    = "2026",
        license = "GNU GPL, v3 or later",
        layer   = 0,
        enabled = true
    }
end

local DEBUG = false

-- ── Loaded in Initialize ──────────────────────────────────────────────────────
local BP_PLACER   = nil
local BUILD_ORDER = nil
local NANO        = nil   -- nano_broker: single owner of every nano order

-- ── State ─────────────────────────────────────────────────────────────────────
local myTeamID    = nil
local commanderID = nil
local botLabID    = nil
local baseX, baseZ = nil, nil
local currentFrame = 0

local distState     = nil
local startPending  = false   -- anchor known, waiting for START_FRAME
local conBot1ID     = nil
local conBots       = {}      -- every con bot the build order produced
local conBotsSentOut = false
local conCount      = 0       -- con bots finished
local pendingCons   = {}      -- unitID -> true while still inside the lab
local pendingStops  = {}      -- {unitID, fireFrame}: deferred CMD_STOP orders
local conDefID      = nil
local con2Frame     = nil     -- frame at which con #2 gets queued
local con2Queued    = false
local nanoAssistDone = false
local comGuardTarget = nil    -- unitID the commander is currently guarding
local labReclaimGated = true  -- hold the reclaim step until con #2 exists

-- ── Hand-off / grid expansion ────────────────────────────────────────────────
local MEX_GRID_BP     = nil
local GRID_SPACING    = nil
local bankFrames      = 0
local handoffStarted  = false
local airLabDefID     = nil
local airLabID        = nil
local airLabItem      = nil   -- the queue item for the hand-off lab
local airLabFrame     = nil   -- frame it was queued, for the watchdog below
local airLabWarned    = false
local airLabRetries   = 0

-- Vehicle plant (base defence), see "Vehicle plant for base defence" below.  Declared
-- up here because DispatchConBots reserves its builder before that section.
local vpQueued        = false
local vpDefID         = nil
local vpBuilder       = nil   -- a con bot held back from the radar trip to build it
local vpOrderFrame    = nil
local vpBuilt         = false
local airConDefID     = nil
local gridStates      = {}    -- one single-builder placer state per grid
local freeAirCons     = {}    -- air cons waiting for a grid
local pendingGrids    = {}    -- {anchorX, anchorZ, rotation} waiting for an air con
local assignedAnchors = {}    -- "x,z" -> true, every cell ever claimed
local completedAnchors = {}   -- {anchorX, anchorZ} list for FindAllValidPlacements
local completedKeys   = {}
local gridRotation    = {}    -- "x,z" -> rotation the grid was placed with
local allGridAnchors  = {}    -- every grid ever assigned: {anchorX, anchorZ, key}
local gridsAssigned   = 0     -- how many grids have been handed to a con
local airConsOrdered  = 0     -- T1 air cons ordered from the air lab, not yet finished
local lastReserveOrder = -1e9
local pendingSince    = {}    -- grid key -> frame it was queued (for the wait log)
local gridWaitSum, gridWaitN = 0, 0
local pendingCapstones = {}   -- capstones the grid's own con could not build
local capstoneJobs    = {}    -- one-item placer states building those
local UPGRADE_BP      = nil
local upgradeStates   = {}    -- retrofit placer states
local upgradedKeys    = {}    -- grids already assigned a retrofit
local gridFinished    = {}    -- grids whose own build order is COMPLETE
local freeT2Cons      = {}    -- T2 air cons waiting for a grid to upgrade
local retrofitPaused  = false
local consolidateOn   = false   -- unit cap is tight: stop building wind, start eating it
local consolidateJobs = {}      -- placer states replacing a 2x2 wind block
local consolidatedKeys = {}     -- "x,z" block centres already claimed
local windBlocks      = {}      -- found-but-unconverted blocks: {cx,cz,key,winds}
local windDefID       = nil
local reclaimingWinds = {}      -- windID -> true while nanos are eating it

-- ── Nano army/eco split ──────────────────────────────────────────────────────
local factories   = {}    -- unitID -> true, every finished factory we own
local armyNanos   = {}    -- unitID -> factoryID it was assigned to assist
local lastArmyLog = nil

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function IsCommander(uDefID)
    local d = uDefID and UnitDefs[uDefID]
    if not d then return false end
    return d.customParams ~= nil
        and (d.customParams.iscommander ~= nil or d.customParams.is_commander ~= nil)
end

local function IsGroundCon(d)
    return d ~= nil and d.isBuilder and not d.canFly and not d.isFactory
       and d.speed and d.speed > 0
end

local function FindConBotDefID(labDefID)
    local d = UnitDefs[labDefID]
    if not d or not d.buildOptions then return nil end
    local best, bestCost = nil, math.huge
    for _, optID in ipairs(d.buildOptions) do
        local od = UnitDefs[optID]
        if IsGroundCon(od) then
            local cost = od.metalCost or 999999
            if cost < bestCost then bestCost = cost; best = optID end
        end
    end
    return best
end

-- A factory that can build a flying constructor.  Faction-agnostic: ask the unit
-- defs rather than hard-coding "corap".
-- The cheapest air factory that at least one builder we ACTUALLY OWN can place.
-- Asking only the commander (or falling back to a hard-coded name) can pick a def
-- none of our builders can build: the placer then never claims it, and the item
-- sits in the queue forever without a word.
local function FindAirFactoryDefID()
    local candidates = {}
    if commanderID and spGetUnitDefID(commanderID) then
        candidates[#candidates + 1] = commanderID
    end
    for _, b in ipairs((distState and distState.builders) or {}) do
        candidates[#candidates + 1] = b
    end

    local best, bestCost = nil, math.huge
    for _, uid in ipairs(candidates) do
        local bdID = spGetUnitDefID(uid)
        local bd   = bdID and UnitDefs[bdID]
        if bd and bd.buildOptions then
            for _, optID in ipairs(bd.buildOptions) do
                local od = UnitDefs[optID]
                if od and od.isFactory and od.buildOptions then
                    for _, subID in ipairs(od.buildOptions) do
                        local sd = UnitDefs[subID]
                        if sd and sd.isBuilder and sd.canFly and not sd.isFactory then
                            local cost = od.metalCost or math.huge
                            if cost < bestCost then bestCost = cost; best = optID end
                            break
                        end
                    end
                end
            end
        end
    end
    return best
end

local function FindAirConDefID(labDefID)
    local d = labDefID and UnitDefs[labDefID]
    if not d or not d.buildOptions then return nil end
    for _, optID in ipairs(d.buildOptions) do
        local od = UnitDefs[optID]
        if od and od.isBuilder and od.canFly and not od.isFactory then return optID end
    end
    return nil
end

-- Somewhere for the air lab that the nanos we already own can reach: the point is
-- for it to go up immediately, not for a con to fly out and build it alone.
-- Half-extent of a def's footprint in elmos (xsize counts 8-elmo half-cells).
local function HalfExtent(defID)
    local ud = defID and UnitDefs[defID]
    if not ud then return 0 end
    return math.max((ud.xsize or 0) * 8, (ud.zsize or ud.ysize or 0) * 8) / 2
end

-- Does this spot collide with anything the build order still intends to place?
-- The kickstarter is usually still filling in when the hand-off fires, so a spot
-- that is free right now can be built over minutes later -- which is exactly how
-- the air lab ended up skipped.
local function ClashesWithBuildOrder(cx, cz, half)
    if not (BUILD_ORDER and BUILD_ORDER.layout) then return false end
    for _, u in ipairs(BUILD_ORDER.layout) do
        if u.a ~= "reclaim" then
            local ud = UnitDefNames[u.n]
            if ud then
                local h = HalfExtent(ud.id)
                if math.abs(cx - (baseX + u.x)) < half + h
                   and math.abs(cz - (baseZ + u.z)) < half + h then
                    return true
                end
            end
        end
    end
    return false
end

local function FindAirLabSpot()
    if not airLabDefID then return nil end
    local labHalf = HalfExtent(airLabDefID)
    local bestX, bestZ, bestNanos = nil, nil, -1
    for r = 96, 560, 48 do
        for a = 0, 11 do
            local ang = a * math.pi / 6
            -- Snap through the placer so the lab lands on a legal build position
            -- for ITS footprint, not just a multiple of 16.
            local x, z = BP_PLACER.SnapToBuildGrid(airLabDefID,
                             baseX + r * math.cos(ang), baseZ + r * math.sin(ang))
            local y = spGetGroundHeight(x, z) or 0
            local ok = Spring.TestBuildOrder(airLabDefID, x, y, z, 0)
            -- The spot must also stay reachable for a ground con once the rest of the
            -- kickstart is up: a lab sealed inside the spiral is never built.
            if ok and ok ~= 0 and not ClashesWithBuildOrder(x, z, labHalf)
               and BP_PLACER.SpotReachable(distState, airLabDefID, x, z) then
                local n = BP_PLACER.CountNanosInRange(x, z)
                if n > bestNanos then bestX, bestZ, bestNanos = x, z, n end
                if n >= AIR_LAB_MIN_NANOS then return x, z, n end
            end
        end
    end
    return bestX, bestZ, bestNanos
end

local function StopGuard()
    if comGuardTarget and commanderID and spGetUnitDefID(commanderID) then
        spGiveOrderToUnit(commanderID, CMD_STOP, {}, {})
    end
    comGuardTarget = nil
end

local function Guard(targetID)
    if comGuardTarget == targetID then return end
    spGiveOrderToUnit(commanderID, CMD_GUARD, {targetID}, {})
    comGuardTarget = targetID
    if DEBUG then Spring.Echo("[MC] commander guards " .. tostring(targetID)) end
end

-- ── Blueprint start ───────────────────────────────────────────────────────────

local function StartBuildOrder()
    local cx, _, cz = spGetUnitPosition(commanderID)
    if not cx then return end
    baseX = math.floor(cx / 16 + 0.5) * 16 + ANCHOR_OFFSET_X
    baseZ = math.floor(cz / 16 + 0.5) * 16 + ANCHOR_OFFSET_Z
    startPending = true
    if DEBUG then Spring.Echo("[MC] anchor " .. baseX .. "," .. baseZ) end
end

local function BeginBuildOrder()
    distState = BP_PLACER.NewDistributed(BUILD_ORDER, baseX, baseZ, 0)
    -- Ground cons can wall themselves in with the kickstart's own buildings; this frees
    -- them and holds back placements that would do it (bar_framework/escape_guard.lua).
    BP_PLACER.EnableEscapeGuard(distState)
    BP_PLACER.AddBuilder(distState, commanderID)
    startPending = false
    if DEBUG then
        Spring.Echo("[MC] build order started, " .. #distState.queue .. " items")
    end
end

-- ── Phase logic ───────────────────────────────────────────────────────────────

-- The reclaim step sits right after nano #2 in the build order, but reclaiming
-- the lab before con bot #2 has rolled out would cost us that con entirely.
local function GateLabReclaim(frame)
    if not labReclaimGated then return end
    for i = 1, #distState.queue do
        local item = distState.queue[i]
        if item.act == "reclaim" then
            if conCount >= 2 then
                item.deferUntil  = nil
                labReclaimGated  = false
                if DEBUG then Spring.Echo("[MC] lab reclaim released") end
            else
                item.deferUntil = frame + 300
            end
            return
        end
    end
    labReclaimGated = false   -- no reclaim step in this blueprint
end

local function UpdateCommanderPhase(frame, resources)
    if not commanderID or not spGetUnitDefID(commanderID) then
        commanderID = nil
        return
    end

    -- Whatever we were guarding is gone (con died, lab reclaimed) — GUARD has
    -- already self-terminated, so take the commander back.
    if comGuardTarget and not spGetUnitDefID(comGuardTarget) then
        comGuardTarget = nil
        BP_PLACER.AddBuilder(distState, commanderID)
    end

    if not nanoAssistDone then
        if BP_PLACER.CountBuilt(distState, "nano") >= NANO_ASSIST_NUM then
            nanoAssistDone = true
            StopGuard()
            BP_PLACER.AddBuilder(distState, commanderID)
            if DEBUG then Spring.Echo("[MC] nano assist done, commander rejoins pool") end
        elseif conBot1ID and spGetUnitDefID(conBot1ID) then
            local claim = BP_PLACER.GetClaim(distState, conBot1ID)
            -- Only hand over between items, so the commander never abandons a
            -- frame that has no nano in range to finish it.
            if claim and claim.cls == "nano"
               and BP_PLACER.GetClaim(distState, commanderID) == nil then
                BP_PLACER.RemoveBuilder(distState, commanderID)
                Guard(conBot1ID)
            end
            return
        end
    end

    if comGuardTarget == conBot1ID and comGuardTarget ~= nil then return end

    -- Nothing the commander can build right now (typically the next item is a
    -- nano): assist the lab so the next con bot comes out sooner.
    local hasWork = BP_PLACER.GetClaim(distState, commanderID) ~= nil
                 or BP_PLACER.HasClaimable(distState, commanderID, frame, resources)
    if hasWork then
        if comGuardTarget == botLabID and comGuardTarget ~= nil then
            StopGuard()
            BP_PLACER.AddBuilder(distState, commanderID)
        end
    elseif botLabID and spGetUnitDefID(botLabID) and comGuardTarget == nil then
        BP_PLACER.RemoveBuilder(distState, commanderID)
        Guard(botLabID)
    end
end

-- ── Grid expansion (starts once the air lab is up) ──────────────────────────

local TryExpand         -- forward declaration
local TryAssignUpgrades -- ditto: the grid onComplete closure below calls it, and a
                        -- local declared later would resolve to a nil global there

local function AnchorKey(ax, az) return tostring(ax) .. "," .. tostring(az) end

local function AddCompletedAnchor(ax, az)
    local key = AnchorKey(ax, az)
    if not completedKeys[key] then
        completedKeys[key] = true
        completedAnchors[#completedAnchors + 1] = {anchorX = ax, anchorZ = az}
    end
end

local function QueueAirCon()
    if airLabID and spGetUnitDefID(airLabID) and airConDefID then
        spGiveOrderToUnit(airLabID, -airConDefID, {0}, {})
        airConsOrdered = airConsOrdered + 1
    end
end

-- Keep AIR_CON_RESERVE cons beyond what the pending grids need, ready or on order.
-- Counted from our own orders, not read back from the factory queue: that read lags on
-- the client process (lab_controller, LAB_ORDER_GRACE).  Off once the unit cap is tight.
local function KeepAirConReserve()
    if consolidateOn or not airLabID or not airConDefID then return end
    if currentFrame - lastReserveOrder < 90 then return end
    if #freeAirCons + airConsOrdered < #pendingGrids + AIR_CON_RESERVE then
        QueueAirCon()
        lastReserveOrder = currentFrame
    end
end

-- Swap the blueprint's factory entry for this grid's capstone.  Returns nothing;
-- if the grid's con cannot build it, the entry is retired from the grid's queue
-- and queued for a builder that can.
local function ApplyCapstone(st, gridIndex, conID)
    local name = CAPSTONE_PLAN[gridIndex] or CAPSTONE_DEFAULT
    local ud   = UnitDefNames[name]
    if not ud then return end

    for _, item in ipairs(st.queue) do
        if item.cls == "factory" then
            if item.n ~= name then
                item.n     = name
                item.defID = ud.id
                item.wx, item.wz = BP_PLACER.SnapToBuildGrid(ud.id, item.wx, item.wz)
                -- Keep cls as "factory" whatever the capstone actually is: that is
                -- what deferFactories keys off, and a capstone should still be the
                -- last thing a grid builds.
                item.cls = "factory"
            end
            local conDef = spGetUnitDefID(conID)
            if conDef and BP_PLACER.CanBuild(conDef, ud.id) then
                if name ~= CAPSTONE_DEFAULT then
                    Spring.Echo(string.format("[MC] grid %d capstone: %s (own con)",
                        gridIndex, name))
                end
            else
                -- Not this con's job.  Retire it here so the grid can still finish,
                -- and hand the position to whoever can place it.
                item.built  = true
                item.status = "skipped"
                pendingCapstones[#pendingCapstones + 1] =
                    {name = name, x = item.wx, z = item.wz, f = item.f or 0,
                     gridIndex = gridIndex}
                Spring.Echo(string.format(
                    "[MC] grid %d capstone: %s at (%d, %d) needs another builder",
                    gridIndex, name, item.wx, item.wz))
            end
            return
        end
    end
end

-- Hand queued capstones to any free builder that can actually place them.
local function TryAssignCapstones()
    local i = 1
    while i <= #pendingCapstones do
        local job = pendingCapstones[i]
        local ud  = UnitDefNames[job.name]
        local taken = false
        if ud then
            for ci, conID in ipairs(freeT2Cons) do
                local cdef = spGetUnitDefID(conID)
                if not cdef then
                    table.remove(freeT2Cons, ci)
                    break
                elseif BP_PLACER.CanBuild(cdef, ud.id) then
                    table.remove(freeT2Cons, ci)
                    table.remove(pendingCapstones, i)
                    spGiveOrderToUnit(conID, CMD_STOP, {}, {})
                    local st = BP_PLACER.New(
                        {layout = {{n = job.name, x = 0, z = 0, f = job.f}}},
                        conID, job.x, job.z, 0, {})
                    capstoneJobs[#capstoneJobs + 1] = st
                    Spring.Echo(string.format(
                        "[MC] capstone %s started at (%d, %d) by con %d",
                        job.name, job.x, job.z, conID))
                    taken = true
                    break
                end
            end
        end
        if not taken then i = i + 1 end
    end
end

local function TryAssignGrids()
    while #freeAirCons > 0 and #pendingGrids > 0 do
        local conID = table.remove(freeAirCons, 1)
        if spGetUnitDefID(conID) then
            spGiveOrderToUnit(conID, CMD_STOP, {}, {})
            local g  = table.remove(pendingGrids, 1)
            local gkey = AnchorKey(g.anchorX, g.anchorZ)
            if pendingSince[gkey] then
                local wait = currentFrame - pendingSince[gkey]
                gridWaitSum, gridWaitN = gridWaitSum + wait, gridWaitN + 1
                Spring.Echo(string.format("[MC] grid %d at (%d, %d) waited %.1fs for a con "
                    .. "(mean %.1fs)", gridsAssigned + 1, g.anchorX, g.anchorZ, wait / 30,
                    gridWaitSum / gridWaitN / 30))
            end
            gridRotation[gkey] = g.rotation
            allGridAnchors[#allGridAnchors + 1] =
                {anchorX = g.anchorX, anchorZ = g.anchorZ, key = gkey}
            local st = BP_PLACER.New(MEX_GRID_BP, conID, g.anchorX, g.anchorZ,
                                     g.rotation, GridInterrupts())
            -- The grid's own factory is the last thing built, unless metal is piling
            -- up unspent -- that is what the "float" interrupt is for.
            st.deferFactories  = true
            st.handoffProgress = GRID_HANDOFF
            gridsAssigned = gridsAssigned + 1
            ApplyCapstone(st, gridsAssigned, conID)
            if consolidateOn and windDefID then
                st.skipDefIDs = {[windDefID] = true}
            end
            st.onNanoThreshold = function(gs)
                AddCompletedAnchor(gs.anchorX, gs.anchorZ)
                TryExpand()
            end
            -- 70% built is enough to start retrofitting: the grid's nanos are up by
            -- then, and its own con is off finishing the last few outlying items.
            -- Waiting for `done` meant one grid in a whole game qualified.
            st.onMostlyDone = function(gs)
                local key = AnchorKey(gs.anchorX, gs.anchorZ)
                if not gridFinished[key] then
                    gridFinished[key] = true
                    Spring.Echo(string.format(
                        "[MC] grid (%d, %d) mostly built -- retrofit eligible",
                        gs.anchorX, gs.anchorZ))
                    TryAssignUpgrades()
                end
            end
            st.onComplete = function(gs)
                AddCompletedAnchor(gs.anchorX, gs.anchorZ)
                gridFinished[AnchorKey(gs.anchorX, gs.anchorZ)] = true
                local skipped = 0
                for _, it in ipairs(gs.queue) do
                    if it.status == "skipped" then skipped = skipped + 1 end
                end
                Spring.Echo(string.format(
                    "[MC] grid (%d, %d) finished: %d items, %d skipped -- retrofit eligible",
                    gs.anchorX, gs.anchorZ, #gs.queue, skipped))
                TryExpand()
                TryAssignUpgrades()
            end
            gridStates[#gridStates + 1] = st
            if DEBUG then
                Spring.Echo(string.format("[MC] grid assigned to con %d at (%d, %d)",
                    conID, g.anchorX, g.anchorZ))
            end
        end
    end
end

TryExpand = function()
    if not MEX_GRID_BP or #completedAnchors == 0 then return end
    -- Once the cap is the constraint, more grid is the wrong thing to spend it on:
    -- the remaining headroom has to stay free for army.
    if consolidateOn then return end
    for _, r in ipairs(BP_PLACER.FindAllValidPlacements(MEX_GRID_BP, completedAnchors)) do
        local key = AnchorKey(r.anchorX, r.anchorZ)
        if not assignedAnchors[key] then
            assignedAnchors[key] = true
            pendingGrids[#pendingGrids + 1] = r
            pendingSince[key] = currentFrame
            QueueAirCon()
        end
    end
    TryAssignGrids()
end

-- Seed the first ring of grids around the opening cluster.
local function StartGridExpansion()
    airConDefID = FindAirConDefID(spGetUnitDefID(airLabID))
    if not airConDefID then
        Spring.Echo("[MC] air lab has no air constructor to build")
        return
    end
    -- The opening cluster owns the middle cell; never try to grid over it.
    assignedAnchors[AnchorKey(baseX, baseZ)] = true
    AddCompletedAnchor(baseX, baseZ)

    local dirs = {
        { GRID_SPACING, 0}, {-GRID_SPACING, 0},
        {0,  GRID_SPACING}, {0, -GRID_SPACING},
    }
    for _, d in ipairs(dirs) do
        local ax, az = baseX + d[1], baseZ + d[2]
        assignedAnchors[AnchorKey(ax, az)] = true
        -- Face the opening cluster, so this grid's first nano is inside the reach of
        -- the nanos already standing there and goes up in seconds.
        local rot = BP_PLACER.BestRotation(MEX_GRID_BP, ax, az, baseX, baseZ)
        pendingGrids[#pendingGrids + 1] = {anchorX = ax, anchorZ = az, rotation = rot}
        pendingSince[AnchorKey(ax, az)] = currentFrame
        QueueAirCon()
    end
    if DEBUG then Spring.Echo("[MC] grid expansion started, " .. #pendingGrids .. " cells") end
    TryAssignGrids()
end

-- Once the air lab is up the build order is finished with the con bots, and a
-- ground con inside a finished grid is just a unit that cannot get out again.
-- Send them somewhere useful and far away: radar gives 2100 elmos of vision each,
-- and it gets them clear of the grids for good.
local function DispatchConBots()
    if conBotsSentOut then return end
    conBotsSentOut = true
    local rad = UnitDefNames["corrad"]
    if not rad then return end
    local mapX = (Game and Game.mapSizeX) or 8192
    local mapZ = (Game and Game.mapSizeZ) or 8192
    local sent = 0
    for i, cid in ipairs(conBots) do
        if spGetUnitDefID(cid) then
            BP_PLACER.RemoveBuilder(distState, cid)
            -- Keep the first one home for the vehicle plant.  Once these leave for
            -- radar, nothing is left in the build queue to place it (the queue's
            -- builders are gone by now), and it would sit there unbuilt.
            -- (No `goto continue` here: Spring runs Lua 5.1, which has no goto, and a
            -- syntax error takes the whole macro controller down silently.)
            local reserve = not vpQueued and not vpBuilder
            if reserve then vpBuilder = cid end
            local placed = false
            for r = reserve and 1e9 or 1600, 3200, 400 do   -- reserved: skip the search
                for a = 0, 7 do
                    local ang = (a + i * 0.5) * math.pi / 4
                    local x = baseX + r * math.cos(ang)
                    local z = baseZ + r * math.sin(ang)
                    if x > 256 and z > 256 and x < mapX - 256 and z < mapZ - 256 then
                        local sx, sz = BP_PLACER.SnapToBuildGrid(rad.id, x, z)
                        local sy = spGetGroundHeight(sx, sz) or 0
                        local ok = Spring.TestBuildOrder(rad.id, sx, sy, sz, 0)
                        if ok and ok ~= 0 then
                            spGiveOrderToUnit(cid, -rad.id, {sx, sy, sz, 0}, {})
                            placed, sent = true, sent + 1
                            break
                        end
                    end
                end
                if placed then break end
            end
        end
    end
    if sent > 0 then
        Spring.Echo(string.format("[MC] %d con bot(s) sent out to build radar", sent))
    end
end

-- ── Spend pressure ───────────────────────────────────────────────────────────

-- Under-spending means too few frames are open at once.  Handing a frame to the
-- nanos sooner frees its builder to place the next one, so the whole base has
-- more places to put metal; when metal is short the opposite is wanted.
local function UpdateSpendPressure(resources)
    local mFrac = resources.metalStorage > 0
                  and (resources.metal / resources.metalStorage) or 0
    local underSpending = resources.metalIncome > resources.metalPull * 1.05

    local handoff = GRID_HANDOFF
    if mFrac < BANK_LOW and not underSpending then
        handoff = SPEND_SLOW
    elseif underSpending or mFrac > BANK_HIGH then
        handoff = SPEND_FAST
    end

    for _, st in ipairs(gridStates)      do st.handoffProgress = handoff end
    for _, st in ipairs(upgradeStates)   do st.handoffProgress = handoff end
    for _, st in ipairs(consolidateJobs) do st.handoffProgress = handoff end
end

-- ── Wind consolidation (unit-cap relief) ─────────────────────────────────────

-- Find EVERY unclaimed 2x2 block of finished winds in one pass and cache them.
-- Winds sit on a global 48-elmo lattice, so a block is just a wind plus its
-- neighbours at +WIND_LATTICE in x, z and both.  One scan feeding a list beats
-- rescanning per job: the scan walks every unit we own, so it is the expensive
-- part, while handing blocks out afterwards is free.
local function ScanWindBlocks()
    if not windDefID then return end
    windBlocks = {}
    local at = {}
    for _, uid in ipairs(spGetTeamUnits(myTeamID) or {}) do
        if spGetUnitDefID(uid) == windDefID and not Spring.GetUnitIsBeingBuilt(uid) then
            local x, _, z = spGetUnitPosition(uid)
            if x then
                at[math.floor(x + 0.5) .. "," .. math.floor(z + 0.5)] = uid
            end
        end
    end
    local taken = {}
    for key, uid in pairs(at) do
        if #windBlocks >= CONSOLIDATE_MAX then break end
        local sx, sz = key:match("(-?%d+),(-?%d+)")
        local x, z = tonumber(sx), tonumber(sz)
        local k2 = (x + WIND_LATTICE) .. "," .. z
        local k3 = x .. "," .. (z + WIND_LATTICE)
        local k4 = (x + WIND_LATTICE) .. "," .. (z + WIND_LATTICE)
        if at[k2] and at[k3] and at[k4]
           and not (taken[key] or taken[k2] or taken[k3] or taken[k4]) then
            local cx, cz = x + WIND_LATTICE / 2, z + WIND_LATTICE / 2
            local ckey = math.floor(cx) .. "," .. math.floor(cz)
            if not consolidatedKeys[ckey] then
                taken[key], taken[k2], taken[k3], taken[k4] = true, true, true, true
                windBlocks[#windBlocks + 1] = {
                    cx = cx, cz = cz, key = ckey,
                    winds = {uid, at[k2], at[k3], at[k4]},
                }
            end
        end
    end
end

-- Condemn a rationed number of winds and put every nano that can reach each one
-- onto reclaiming it.  Rationing matters: reclaiming the lot at once would drop a
-- large slice of energy income in one go.
local function UpdateWindReclaim()
    if not windDefID then
        windDefID = UnitDefNames["corwin"] and UnitDefNames["corwin"].id
        if not windDefID then return end
    end
    local maxU = Spring.GetTeamMaxUnits and Spring.GetTeamMaxUnits(myTeamID)
    local cnt  = Spring.GetTeamUnitCount and Spring.GetTeamUnitCount(myTeamID)
    if not (maxU and cnt) then return end
    if (maxU - cnt) > maxU * RECLAIM_TRIGGER_FRAC then return end

    local active = 0
    for wid in pairs(reclaimingWinds) do
        if spGetUnitDefID(wid) then active = active + 1 else reclaimingWinds[wid] = nil end
    end
    local budget = math.max(1, math.floor(maxU * RECLAIM_BUDGET_FRAC))
    if active >= budget then return end

    local ordered = 0
    for _, uid in ipairs(spGetTeamUnits(myTeamID) or {}) do
        if active >= budget then break end
        if spGetUnitDefID(uid) == windDefID and not reclaimingWinds[uid]
           and not Spring.GetUnitIsBeingBuilt(uid) then
            local x, _, z = spGetUnitPosition(uid)
            if x then
                local nanos = BP_PLACER.NanosInRange(x, z)
                local used = 0
                -- Every nano that can reach it: partly build power, but mainly so
                -- none is left idle nearby to repair what we are removing.  This is
                -- the highest priority there is, so it displaces assist and balance
                -- work without the callers needing to know about each other.
                for _, nid in ipairs(nanos) do
                    if NANO.Reclaim(NANO.PRIO.WIND_RECLAIM, nid, uid) then
                        used = used + 1
                    end
                end
                if used > 0 then
                    reclaimingWinds[uid] = true
                    active  = active + 1
                    ordered = ordered + 1
                end
            end
        end
    end
    if DEBUG and ordered > 0 then
        Spring.Echo(string.format("[MC] wind reclaim: %d condemned (%d active, budget %d)",
            ordered, active, budget))
    end
end

-- Replace the block with whichever resource is scarcer right now.
local function ConsolidationUnit(resources)
    local mFrac = resources.metalStorage  > 0 and (resources.metal  / resources.metalStorage)  or 1
    local eFrac = resources.energyStorage > 0 and (resources.energy / resources.energyStorage) or 1
    if eFrac <= mFrac then return "corfus" end
    return "cormoho"
end

local function StartConsolidation(conID, resources)
    local block = nil
    while #windBlocks > 0 do
        local b = table.remove(windBlocks, 1)
        if not consolidatedKeys[b.key] then block = b; break end
    end
    if not block then return false end
    local cx, cz, ckey = block.cx, block.cz, block.key
    local name = ConsolidationUnit(resources)
    local ud = UnitDefNames[name]
    if not ud or not BP_PLACER.CanBuild(spGetUnitDefID(conID), ud.id) then return false end

    consolidatedKeys[ckey] = true
    spGiveOrderToUnit(conID, CMD_STOP, {}, {})
    -- A one-item blueprint.  clearBlockers does the rest: the new building overlaps
    -- all four winds, so the placer reclaims them (with any nanos in range) and
    -- then builds in the space they leave.
    local bp = {layout = {{n = name, x = 0, z = 0, f = 0}}}
    local st = BP_PLACER.New(bp, conID, cx, cz, 0, {})
    st.clearBlockers = true
    -- ONLY wind.  Anything else in the footprint (a nano, or the fusion we just
    -- placed) must never be reclaimed to make room.
    st.clearOnlyDefIDs = {[windDefID] = true}
    consolidateJobs[#consolidateJobs + 1] = st
    Spring.Echo(string.format("[MC] consolidating 4 winds at (%d, %d) into %s",
        cx, cz, name))
    return true
end

-- ── Retrofit (T2 upgrade of a finished grid) ─────────────────────────────────

-- A T2 con is one that can build what the upgrade blueprint asks for.  Asking the
-- unit defs beats hard-coding "coraca": it is the same question the placer will
-- ask when it tries to claim an item.
local function IsT2Con(defID)
    if not (UPGRADE_BP and UPGRADE_BP.layout and UPGRADE_BP.layout[1]) then return false end
    local ud = UnitDefNames[UPGRADE_BP.layout[1].n]
    return ud and BP_PLACER.CanBuild(defID, ud.id) or false
end

TryAssignUpgrades = function()
    if not UPGRADE_BP then return end
    while #freeT2Cons > 0 do
        local conID = freeT2Cons[1]
        if not spGetUnitDefID(conID) then
            table.remove(freeT2Cons, 1)
        else
            -- Nearest finished grid that has not been retrofitted yet.
            local cx, _, cz = spGetUnitPosition(conID)
            local best, bestD2, bestKey = nil, math.huge, nil
            for _, a in ipairs(completedAnchors) do
                local key = AnchorKey(a.anchorX, a.anchorZ)
                -- Only grids that finished their own blueprint: a grid still
                -- building would be competing with its own retrofit for metal.
                if gridFinished[key] and not upgradedKeys[key]
                   and key ~= AnchorKey(baseX, baseZ) then
                    local dx, dz = (cx or 0) - a.anchorX, (cz or 0) - a.anchorZ
                    local d2 = dx * dx + dz * dz
                    if d2 < bestD2 then best, bestD2, bestKey = a, d2, key end
                end
            end
            if not best then return end          -- nothing ripe; keep the con waiting
            table.remove(freeT2Cons, 1)
            upgradedKeys[bestKey] = true
            spGiveOrderToUnit(conID, CMD_STOP, {}, {})
            local st = BP_PLACER.New(UPGRADE_BP, conID, best.anchorX, best.anchorZ,
                                     gridRotation[bestKey] or 0,
                                     GridInterrupts())
            st.clearBlockers   = true    -- reclaim the mex/winds the fusions need
            -- A retrofit clears exactly what the upgrade layout sits on top of:
            -- the T1 mex it replaces and the corner winds the fusion needs.
            st.clearOnlyDefIDs = {}
            for _, n in ipairs({"corwin", "cormex"}) do
                local ud = UnitDefNames[n]
                if ud then st.clearOnlyDefIDs[ud.id] = true end
            end
            st.handoffProgress = GRID_HANDOFF
            -- Hand the con straight to the next grid instead of retiring it.
            st.onComplete = function(us)
                if us.builderID and spGetUnitDefID(us.builderID) then
                    freeT2Cons[#freeT2Cons + 1] = us.builderID
                    TryAssignUpgrades()
                end
            end
            upgradeStates[#upgradeStates + 1] = st
            Spring.Echo(string.format("[MC] retrofit started at (%d, %d) by con %d",
                best.anchorX, best.anchorZ, conID))
        end
    end
end

-- ── Hand-off ─────────────────────────────────────────────────────────────────

-- Metal is banking: the build order cannot spend what the economy earns any more.
-- Put an air lab up inside the nanos' reach and let the grid system take over.
local function StartHandoff()
    handoffStarted = true
    airLabDefID = FindAirFactoryDefID()
    if not airLabDefID then
        Spring.Echo("[MC] hand-off: no builder we own can place an air factory")
        return
    end
    local x, z, nanos = FindAirLabSpot()
    if not x then
        Spring.Echo("[MC] hand-off: nowhere to put the air lab")
        handoffStarted = false
        return
    end
    local name = UnitDefs[airLabDefID] and UnitDefs[airLabDefID].name
    local item = BP_PLACER.InsertPriorityItem(distState, name, x, z, 0)
    if not item then
        Spring.Echo("[MC] hand-off: could not queue " .. tostring(name))
        handoffStarted = false
        return
    end
    airLabItem  = item
    airLabFrame = currentFrame
    -- Not DEBUG-gated: this is the one event that decides whether the bot scales,
    -- and a silent success is indistinguishable from a silent failure.
    Spring.Echo(string.format(
        "[MC] HAND-OFF frame=%d: %s at (%d, %d), %d nanos in range, %d builders",
        currentFrame, tostring(name), x, z, nanos or 0, #distState.builders))
end

-- ── Vehicle plant for base defence ───────────────────────────────────────────

-- The one army-driven change to the economy: a T1 vehicle plant, whose output is the
-- bot's ground defence.  corvp, not the T2 bot lab -- ~16k energy for a T2 lab at
-- ~3 min is out of reach, and the lab is only the start; the defenders still have to
-- be built after it.
--
-- WHEN is derived, not hardcoded.  Raid arrival times measured in one match carry
-- that match's spawn distance: in-line spawns land a ground raid ~28 s sooner than
-- the cross-position runs they were measured on.  So we store the part that does
-- not depend on spawns -- how long an early ground raid spends BUILDING -- and add
-- this match's actual travel time.  From GROUND_RAIDER_BOT's ~6:30 arrival (frame
-- 11700) across 12,968 elmos at corgator speed 85: 11700 - 4577 = ~7120 frames.
local VP_NAME           = "corvp"
local GROUND_RAID_BUILD = 7120   -- frames, spawn-independent
local GROUND_RAID_SPEED = 85     -- elmos/s, the early raider
local VP_LEAD_FRAMES    = 3600   -- lab + first defenders need this long before arrival
local VP_WATCHDOG       = 1800   -- ordered but no plant this long later: try again
-- (vpQueued / vpDefID / vpBuilder / vpOrderFrame / vpBuilt are declared with the
--  air-lab state near the top: DispatchConBots needs them, and a second `local`
--  here would silently create separate variables for everything below.)

-- Can any builder we actually own place this def?  Queueing one nobody can build
-- sits in the placer forever without a word (the air-lab lesson above).
local function OwnedBuilderCanBuild(defID)
    local candidates = {}
    if commanderID and spGetUnitDefID(commanderID) then candidates[1] = commanderID end
    for _, b in ipairs((distState and distState.builders) or {}) do
        candidates[#candidates + 1] = b
    end
    for _, uid in ipairs(candidates) do
        local bd = UnitDefs[spGetUnitDefID(uid) or -1]
        for _, optID in ipairs((bd and bd.buildOptions) or {}) do
            if optID == defID then return true end
        end
    end
    return false
end

-- Frame to start the plant by: estimated ground-raid arrival minus the lead needed.
local function VehicleLabDeadline()
    local mb   = WG and WG.MetalBot
    local dist = mb and mb.foeDist
    if (not dist or dist <= 0) and baseX then
        -- Symmetric-map mirror, the same fallback map_model uses.
        local ex, ez = (Game.mapSizeX or 0) - baseX, (Game.mapSizeZ or 0) - baseZ
        dist = math.sqrt((ex - baseX) ^ 2 + (ez - baseZ) ^ 2)
    end
    local arrival = GROUND_RAID_BUILD + ((dist or 0) / GROUND_RAID_SPEED) * 30
    return arrival - VP_LEAD_FRAMES
end

-- Ground factories need room for what they build to leave, so search further out
-- than the air lab (which spawns aircraft and can sit anywhere) and away from the
-- dense kickstart spiral around the commander.
local function FindVehicleLabSpot()
    local half = HalfExtent(vpDefID)
    for r = 400, 1000, 60 do
        for a = 0, 11 do
            local ang = a * math.pi / 6
            local x, z = BP_PLACER.SnapToBuildGrid(vpDefID,
                             baseX + r * math.cos(ang), baseZ + r * math.sin(ang))
            local y  = spGetGroundHeight(x, z) or 0
            local ok = Spring.TestBuildOrder(vpDefID, x, y, z, 0)
            if ok and ok ~= 0 and not ClashesWithBuildOrder(x, z, half)
               and BP_PLACER.SpotReachable(distState, vpDefID, x, z) then
                return x, z
            end
        end
    end
    return nil
end

local function CanBuild(builderID, defID)
    local bd = builderID and UnitDefs[spGetUnitDefID(builderID) or -1]
    for _, optID in ipairs((bd and bd.buildOptions) or {}) do
        if optID == defID then return true end
    end
    return false
end

local function MaybeQueueVehicleLab(frame)
    if vpBuilt or not distState or not baseX then return end
    vpDefID = vpDefID or (UnitDefNames[VP_NAME] and UnitDefNames[VP_NAME].id)
    if not vpDefID then return end

    -- Already ordered: watch for the plant to appear, and retry if it never does
    -- (builder killed on the way, spot taken, order dropped).
    if vpQueued then
        local have = Spring.GetTeamUnitsByDefs and Spring.GetTeamUnitsByDefs(myTeamID, vpDefID)
        if have and #have > 0 then
            vpBuilt = true
        elseif vpOrderFrame and frame - vpOrderFrame > VP_WATCHDOG then
            Spring.Echo(string.format("[MC] vehicle lab: no plant %d frames after ordering, retrying",
                frame - vpOrderFrame))
            vpQueued, vpBuilder = false, nil
        end
        return
    end

    -- Three reasons to start: a ground threat we cannot answer, the derived deadline,
    -- or a con bot freed by the hand-off.  The last is usually first, and it is the
    -- right time anyway: hand-off happens BECAUSE metal is banking, so the plant is
    -- paid for out of surplus, and a ground con left idle among the growing grids
    -- risks being walled in.
    local mb      = WG and WG.MetalBot
    local pulled  = mb and (mb.urgency == "rush" or mb.urgency == "build")
                    and mb.urgencyChannel ~= "air"
    local due     = frame >= VehicleLabDeadline()
    local conFree = vpBuilder and spGetUnitDefID(vpBuilder) and CanBuild(vpBuilder, vpDefID)
    if not (pulled or due or conFree) then return end

    local x, z = FindVehicleLabSpot()
    if not x then return end   -- try again next tick

    local how
    if conFree then
        local y = spGetGroundHeight(x, z) or 0
        spGiveOrderToUnit(vpBuilder, -vpDefID, { x, y, z, 0 }, {})
        how = "reserved con bot"
    elseif OwnedBuilderCanBuild(vpDefID)
           and BP_PLACER.InsertPriorityItem(distState, VP_NAME, x, z, 0) then
        how = "build queue"
    else
        return
    end
    vpQueued, vpOrderFrame = true, frame
    Spring.Echo(string.format(
        "[MC] VEHICLE LAB frame=%d via %s (%s, deadline %d): %s at (%d, %d)",
        frame, how, pulled and "threat" or (conFree and "hand-off" or "timer"),
        math.floor(VehicleLabDeadline()), VP_NAME, x, z))
end

-- ── Nano army/eco balance ────────────────────────────────────────────────────

-- Effective headroom threshold for this game's unit cap.
local function CapSlack(absolute)
    local maxU = Spring.GetTeamMaxUnits and Spring.GetTeamMaxUnits(myTeamID)
    if not maxU or maxU <= 0 then return absolute end
    return math.min(absolute, math.floor(maxU * CAP_SLACK_FRAC))
end

local function IsNanoTurret(defID)
    local d = defID and UnitDefs[defID]
    if not d then return false end
    if not (d.isBuilder and not d.isFactory and not d.canFly) then return false end
    return d.speed == nil or d.speed == 0
end

-- What this builder is actually pouring build power into right now.
local function NanoTarget(uid)
    local t = Spring.GetUnitIsBuilding and Spring.GetUnitIsBuilding(uid)
    if t then return t end
    local cmds = spGetUnitCommands(uid, 1)
    local c = cmds and cmds[1]
    if c and (c.id == CMD_REPAIR or c.id == CMD_GUARD or c.id == CMD_RECLAIM)
       and c.params then
        return c.params[1]
    end
    return nil
end

-- Army spending is anything whose output is a unit: a factory, or a mobile unit
-- under construction.  Everything else -- mex, wind, nano, fusion -- is eco.
local function SpendClass(targetID)
    if not targetID then return nil end
    local d = UnitDefs[spGetUnitDefID(targetID) or -1]
    if not d then return nil end
    if d.isFactory then return "army" end
    if d.speed and d.speed > 0 then return "army" end
    return "eco"
end

local function NanoBuildSpeed(defID)
    local d = UnitDefs[defID]
    return (d and d.buildSpeed) or 0
end

-- Does this factory actually have something queued?  Guarding an idle one spends the
-- nano's build power on nothing: GUARD only assists what the factory is CURRENTLY
-- building, and an empty queue means that's nothing.  The bot lab sits idle like this
-- between con #1 and con #2 (and briefly at the very start) -- a nano switched to
-- "army" there just does nothing until the lab is reclaimed and it falls back to eco.
local function FactoryHasWork(fid)
    if not spGetFactoryCommands then return true end   -- can't tell; assume yes
    local cmds = spGetFactoryCommands(fid, -1)
    return cmds and #cmds > 0
end

-- The nearest factory this nano can physically reach that has something to build;
-- nil if none.
local function FactoryInReach(uid, defID)
    local reach = (UnitDefs[defID] and UnitDefs[defID].buildDistance) or 380
    local ux, _, uz = spGetUnitPosition(uid)
    if not ux then return nil end
    local best, bestD2 = nil, reach * reach
    for fid in pairs(factories) do
        if spGetUnitDefID(fid) then
            if FactoryHasWork(fid) then
                local fx, _, fz = spGetUnitPosition(fid)
                if fx then
                    local dx, dz = ux - fx, uz - fz
                    local d2 = dx * dx + dz * dz
                    if d2 <= bestD2 then best, bestD2 = fid, d2 end
                end
            end
        else
            factories[fid] = nil
        end
    end
    return best
end

local function UpdateNanoBalance(frame)
    -- Headroom: near the unit cap, army is the only thing worth spending on.
    local target = ARMY_SHARE
    local maxUnits = Spring.GetTeamMaxUnits and Spring.GetTeamMaxUnits(myTeamID)
    local count    = Spring.GetTeamUnitCount and Spring.GetTeamUnitCount(myTeamID)
    if maxUnits and count and (maxUnits - count) <= CapSlack(ARMY_CAP_SLACK) then
        target = 1.0
    end

    local armyBP, ecoBP = 0, 0
    local spentArmy, spentEco = 0, 0     -- measured, for reporting
    local ecoPool = {}                   -- nanos available to switch to army
    for _, uid in ipairs(spGetTeamUnits(myTeamID) or {}) do
        local dID = spGetUnitDefID(uid)
        if IsNanoTurret(dID) and not Spring.GetUnitIsBeingBuilt(uid) then
            local bp = NanoBuildSpeed(dID)
            local cls = SpendClass(NanoTarget(uid))
            if cls == "army" then spentArmy = spentArmy + bp
            elseif cls == "eco" then spentEco = spentEco + bp
            end

            if armyNanos[uid] and spGetUnitDefID(armyNanos[uid]) then
                armyBP = armyBP + bp
            else
                armyNanos[uid] = nil
                ecoBP = ecoBP + bp
                -- Counted as eco, but only offered up for reassignment if the
                -- broker would actually hand it over.  No special case needed: the
                -- balancer is the lowest priority there is, so anything on reclaim
                -- or assist work simply is not available.
                if not NANO.IsBusy(uid, NANO.PRIO.BALANCE) then
                    ecoPool[#ecoPool + 1] = {uid = uid, defID = dID, bp = bp}
                end
            end
        end
    end

    local totalBP = armyBP + ecoBP
    if totalBP <= 0 then return end
    local wantBP = target * totalBP
    local moves  = 0

    -- Build power comes in whole nanos, so the exact target is usually unreachable.
    -- Move a nano only when doing so gets us CLOSER to the target than staying put:
    -- comparing shares against a dead band instead made a single nano flip between
    -- 0% and 100% every tick, since neither value is ever within 5% of 30%.
    local function improves(newBP)
        return math.abs(newBP - wantBP) < math.abs(armyBP - wantBP)
    end

    if armyBP < wantBP then
        for _, n in ipairs(ecoPool) do
            if moves >= NANO_MOVES_MAX or not improves(armyBP + n.bp) then break end
            local fid = FactoryInReach(n.uid, n.defID)
            if fid and NANO.Guard(NANO.PRIO.BALANCE, n.uid, fid) then
                armyNanos[n.uid] = fid
                armyBP = armyBP + n.bp
                moves  = moves + 1
            end
        end
    elseif armyBP > wantBP then
        for uid, fid in pairs(armyNanos) do
            if moves >= NANO_MOVES_MAX then break end
            local dID = spGetUnitDefID(uid)
            if dID then
                local bp = NanoBuildSpeed(dID)
                if not improves(armyBP - bp) then break end
                -- Released nanos fall back to assisting whatever is being built
                -- nearby, which is eco work.
                NANO.Release(uid)
                armyNanos[uid] = nil
                armyBP = armyBP - bp
                moves  = moves + 1
            else
                armyNanos[uid] = nil
            end
        end
    end
    local share = armyBP / totalBP

    if DEBUG then
        local spent = spentArmy + spentEco
        local msg = string.format("[MC] nano bp: allocated army %.0f%% (target %.0f%%), "
            .. "actually spending army %.0f%% of %.0f bp, %d factories",
            share * 100, target * 100,
            spent > 0 and (spentArmy / spent * 100) or 0, spent, (function()
                local n = 0; for _ in pairs(factories) do n = n + 1 end; return n end)())
        if msg ~= lastArmyLog then Spring.Echo(msg); lastArmyLog = msg end
    end
end

-- ── Widget callbacks ──────────────────────────────────────────────────────────

function widget:Initialize()
    local ok1, r1 = pcall(VFS.Include, "LuaUI/Widgets/blueprint_placer.lua")
    local ok2, r2 = pcall(VFS.Include,
        "LuaUI/Widgets/blueprints/general/build_order_blueprint.lua")
    if not ok1 then Spring.Echo("[MC] ERROR loading blueprint_placer: "      .. tostring(r1)); return end
    if not ok2 then Spring.Echo("[MC] ERROR loading build_order_blueprint: " .. tostring(r2)); return end
    local ok3, r3 = pcall(VFS.Include,
        "LuaUI/Widgets/blueprints/general/mex_grid_alab.lua")
    if not ok3 then Spring.Echo("[MC] ERROR loading mex_grid_alab: " .. tostring(r3)); return end
    local ok4, r4 = pcall(VFS.Include, "LuaUI/Widgets/blueprints/general/upgrade.lua")
    if ok4 then UPGRADE_BP = r4
    else Spring.Echo("[MC] no upgrade blueprint (" .. tostring(r4) .. "); retrofits disabled") end
    BP_PLACER    = r1
    BUILD_ORDER  = r2
    NANO         = r1.NANO
    MEX_GRID_BP  = r3
    GRID_SPACING = BP_PLACER.GRID_SPACING

    if DEBUG then
        -- Real footprints, to check them against the sizes blueprint_gen assumed.
        for _, n in ipairs({"corwin", "cormex", "cornanotc", "corlab", "corck"}) do
            local ud = UnitDefNames[n]
            if ud then
                Spring.Echo(string.format("[MC] def %s xsize=%s zsize=%s buildDist=%s",
                    n, tostring(ud.xsize), tostring(ud.zsize), tostring(ud.buildDistance)))
            end
        end
    end

    myTeamID = spGetMyTeamID()
    for _, uid in ipairs(Spring.GetTeamUnits(myTeamID) or {}) do
        if IsCommander(spGetUnitDefID(uid)) then
            commanderID = uid
            break
        end
    end
    if commanderID then StartBuildOrder() end
end

function widget:UnitCreated(unitID, unitDefID, teamID, builderID)
    if not myTeamID then myTeamID = spGetMyTeamID() end
    if teamID ~= myTeamID then return end

    -- Must come first: the corlab is itself a queue item, and so is anything
    -- else that would hit an early return below.
    if distState then
        BP_PLACER.OnUnitCreated(distState, unitID, unitDefID, builderID)
    end

    local d = UnitDefs[unitDefID]
    if not d then return end

    if d.isFactory then
        if airLabDefID and unitDefID == airLabDefID and not airLabID then
            airLabID = unitID
            if DEBUG then Spring.Echo("[MC] air lab frame " .. unitID) end
        elseif not botLabID then
            botLabID = unitID
            if DEBUG then Spring.Echo("[MC] bot lab " .. unitID) end
        end
        return
    end

    -- Con bots start life inside the lab; they are only usable once finished.
    if builderID and builderID == botLabID and IsGroundCon(d) then
        pendingCons[unitID] = true
    end
end

function widget:UnitFinished(unitID, unitDefID, teamID)
    if teamID ~= myTeamID then return end
    local d = UnitDefs[unitDefID]

    if IsCommander(unitDefID) and not commanderID then
        commanderID = unitID
        StartBuildOrder()
    end

    -- Lab done → queue con bot #1.  Con #2 is queued CON_GAP_FRAMES after #1
    -- finishes, which is the spacing the sim's build order assumes.
    if unitID == botLabID then
        conDefID = FindConBotDefID(unitDefID)
        if conDefID then spGiveOrderToUnit(botLabID, -conDefID, {0}, {}) end
        if DEBUG then Spring.Echo("[MC] lab finished, con #1 queued") end
    end

    if d and d.isFactory then
        factories[unitID] = true
        -- An advanced air lab can make the T2 con that does retrofits.
        if UPGRADE_BP and unitID ~= airLabID then
            local t2 = FindAirConDefID(unitDefID)
            if t2 and IsT2Con(t2) then
                for _ = 1, UPGRADE_CONS_PER_LAB do
                    spGiveOrderToUnit(unitID, -t2, {0}, {})
                end
            end
        end
    end

    -- Air lab finished -> the grid system takes over from here.
    if unitID == airLabID then
        StartGridExpansion()
        DispatchConBots()
    end

    -- Air cons roll out.  The factory gives them a guard order on itself as they
    -- leave, which arrives AFTER this callback -- so stopping only here leaves them
    -- assisting the lab forever, permanently "busy", and they never take a grid.
    -- Stop now and again once that order has landed.
    if airLabID and d and d.isBuilder and d.canFly and not d.isFactory then
        spGiveOrderToUnit(unitID, CMD_STOP, {}, {})
        pendingStops[#pendingStops + 1] = {unitID = unitID, fireFrame = currentFrame + 30}
        if IsT2Con(unitDefID) then
            freeT2Cons[#freeT2Cons + 1] = unitID
            TryAssignUpgrades()
        else
            airConsOrdered = math.max(0, airConsOrdered - 1)
            freeAirCons[#freeAirCons + 1] = unitID
            TryAssignGrids()
        end
    end

    if pendingCons[unitID] then
        pendingCons[unitID] = nil
        conCount = conCount + 1
        conBots[#conBots + 1] = unitID
        if not conBot1ID then
            conBot1ID = unitID
            con2Frame = currentFrame + CON_GAP_FRAMES
        end
        BP_PLACER.AddBuilder(distState, unitID)
        if DEBUG then Spring.Echo("[MC] con #" .. conCount .. " joined (" .. unitID .. ")") end
    end

    local x, _, z = spGetUnitPosition(unitID)
    if distState then
        BP_PLACER.OnUnitFinished(distState, unitID, unitDefID, x, z)
    end
    for _, gs in ipairs(gridStates) do
        if not gs.done then
            BP_PLACER.OnUnitFinished(gs, unitID, unitDefID, x, z)
        end
    end
    for _, us in ipairs(upgradeStates) do
        if not us.done then
            BP_PLACER.OnUnitFinished(us, unitID, unitDefID, x, z)
        end
    end
    for _, cs in ipairs(consolidateJobs) do
        if not cs.done then
            BP_PLACER.OnUnitFinished(cs, unitID, unitDefID, x, z)
        end
    end
    for _, cs in ipairs(capstoneJobs) do
        if not cs.done then
            BP_PLACER.OnUnitFinished(cs, unitID, unitDefID, x, z)
        end
    end
    -- A nuke silo is a stockpiling weapon, not a factory, so nothing else will
    -- ever tell it to build a missile.  Ask for a few; firing them is not wired up.
    if d and d.canStockpile then
        for _ = 1, 3 do
            spGiveOrderToUnit(unitID, CMD_STOCKPILE, {}, {})
        end
        Spring.Echo("[MC] " .. (d.name or "?") .. " finished: stockpiling")
    end
end

-- Fires when a finished unit actually leaves the factory: the last moment the
-- engine's auto-guard can be applied, so clear it here too.
function widget:UnitFromFactory(unitID, unitDefID, teamID, factID)
    if teamID ~= myTeamID then return end
    if factID and factID == airLabID then
        spGiveOrderToUnit(unitID, CMD_STOP, {}, {})
    end
end

function widget:UnitDestroyed(unitID, unitDefID, teamID)
    if teamID ~= myTeamID then return end
    if DEBUG then
        local x, _, z = spGetUnitPosition(unitID)
        Spring.Echo(string.format("[MC] lost %s id=%s at (%s,%s) f=%d beingBuilt=%s",
            UnitDefs[unitDefID] and UnitDefs[unitDefID].name or "?", tostring(unitID),
            tostring(x and math.floor(x)), tostring(z and math.floor(z)),
            currentFrame, tostring(Spring.GetUnitIsBeingBuilt(unitID))))
    end
    if distState then BP_PLACER.OnUnitDestroyed(distState, unitID) end
    pendingCons[unitID] = nil
    factories[unitID]   = nil
    armyNanos[unitID]   = nil
    if unitID == commanderID then commanderID = nil end
    if unitID == conBot1ID   then conBot1ID   = nil end
    if unitID == botLabID    then botLabID    = nil end
    if unitID == comGuardTarget then comGuardTarget = nil end
end

-- ── GameFrame, split up ──────────────────────────────────────────────────────
-- Lua 5.1 allows a function at most 60 UPVALUES -- every file-level local it
-- mentions is one.  GameFrame grew past that and the widget silently failed to
-- load ("function at line N has more than 60 upvalues").  Each block below is a
-- separate function so the references are spread across several budgets.

local function MaybeQueueCon2(frame)
    if con2Queued or not con2Frame or frame < con2Frame then return end
    if botLabID and spGetUnitDefID(botLabID) and conDefID then
        spGiveOrderToUnit(botLabID, -conDefID, {0}, {})
        con2Queued = true
        if DEBUG then Spring.Echo("[MC] con #2 queued at frame " .. frame) end
    elseif not botLabID then
        con2Queued = true   -- lab gone; nothing to queue from
    end
end

local function FirePendingStops(frame)
    local i = 1
    while i <= #pendingStops do
        local ps = pendingStops[i]
        if frame >= ps.fireFrame then
            if spGetUnitDefID(ps.unitID) then
                spGiveOrderToUnit(ps.unitID, CMD_STOP, {}, {})
            end
            table.remove(pendingStops, i)
        else
            i = i + 1
        end
    end
end

local function UpdateHandoff(frame, resources)
    -- Trigger: metal banked above BANK_FRAC of storage for BANK_HOLD frames, but
    -- only once the economy is real (income rules out the stocked start).
    if not handoffStarted and resources.metalStorage > 0
       and resources.metalIncome >= HANDOFF_MIN_INCOME then
        if (resources.metal / resources.metalStorage) >= BANK_FRAC then
            bankFrames = bankFrames + 10
            if bankFrames >= BANK_HOLD then StartHandoff() end
        else
            bankFrames = 0
        end
    end

    -- Watchdog: queued but nothing has begun building it.
    if airLabItem and not airLabID and airLabFrame and (frame - airLabFrame) > 900 then
        local st = airLabItem.status
        if st == "skipped" or st == "pending" then
            -- The spot was taken (usually by the build order itself).  Try again
            -- elsewhere: without this lab there is no army and no expansion, so
            -- giving up once is giving up for the whole game.
            airLabRetries = (airLabRetries or 0) + 1
            Spring.Echo(string.format(
                "[MC] hand-off retry %d: %s not started (status=%s), picking a new spot",
                airLabRetries, tostring(airLabItem.n), tostring(st)))
            airLabItem.status = "skipped"
            airLabItem.built  = true
            airLabItem = nil
            if airLabRetries <= 5 then
                handoffStarted = false     -- StartHandoff runs again next tick
                bankFrames     = BANK_HOLD -- and fires immediately
            elseif not airLabWarned then
                airLabWarned = true
                Spring.Echo("[MC] hand-off GAVE UP after 5 attempts")
            end
        end
    end
end

local function UpdateGrids(frame, resources)
    local i = 1
    while i <= #gridStates do
        local gs = gridStates[i]
        if gs.done then
            -- Reuse the con: for a new grid, or as a demolition crew once the cap
            -- is tight.  It used to simply vanish from the pool here.
            if gs.builderID and spGetUnitDefID(gs.builderID) then
                freeAirCons[#freeAirCons + 1] = gs.builderID
            end
            table.remove(gridStates, i)
        else
            BP_PLACER.Update(gs, frame, resources)
            i = i + 1
        end
    end
    if #freeAirCons > 0 and #pendingGrids > 0 then TryAssignGrids() end
    KeepAirConReserve()
end

local function CheckCapPressure()
    if consolidateOn then
        if windDefID then
            for _, gs in ipairs(gridStates) do
                gs.skipDefIDs = gs.skipDefIDs or {}
                gs.skipDefIDs[windDefID] = true
            end
        end
        return
    end
    local maxU = Spring.GetTeamMaxUnits and Spring.GetTeamMaxUnits(myTeamID)
    local cnt  = Spring.GetTeamUnitCount and Spring.GetTeamUnitCount(myTeamID)
    if not (maxU and cnt) or (maxU - cnt) > CapSlack(CONSOLIDATE_SLACK) then return end

    consolidateOn = true
    windDefID = UnitDefNames["corwin"] and UnitDefNames["corwin"].id
    -- Every grid becomes retrofit-eligible right now, finished or not.  From here
    -- they stop building wind, so their remaining T1 eco is all they will ever
    -- have -- and a T1->T2 mex upgrade costs no unit cap, so there is nothing to
    -- gain by waiting for a completion that can no longer happen.
    local marked = 0
    for _, g in ipairs(allGridAnchors) do
        if not gridFinished[g.key] then
            gridFinished[g.key] = true
            AddCompletedAnchor(g.anchorX, g.anchorZ)
            marked = marked + 1
        end
    end
    Spring.Echo(string.format(
        "[MC] unit cap tight: grids stop building wind, consolidation on, "
        .. "%d more grids marked for retrofit", marked))
    TryAssignUpgrades()
end

local function UpdateRetrofits(frame, resources)
    -- Retrofits yield to everything else when metal is short: a T2 mex earns less
    -- per metal than a T1, so competing with a normal grid during a stall is
    -- strictly bad.  Stop the builders rather than pausing, or they sit holding a
    -- half-issued order.
    local mFrac = resources.metalStorage > 0
                  and (resources.metal / resources.metalStorage) or 1
    if not retrofitPaused and mFrac < RETROFIT_STALL_FRAC then
        retrofitPaused = true
        for _, us in ipairs(upgradeStates) do
            if us.builderID and spGetUnitDefID(us.builderID) then
                spGiveOrderToUnit(us.builderID, CMD_STOP, {}, {})
                us.currentTask = nil
            end
        end
        if DEBUG then Spring.Echo("[MC] retrofits paused (metal stall)") end
    elseif retrofitPaused and mFrac > RETROFIT_RESUME_FRAC then
        retrofitPaused = false
        if DEBUG then Spring.Echo("[MC] retrofits resumed") end
    end

    if not retrofitPaused then
        local i = 1
        while i <= #upgradeStates do
            local us = upgradeStates[i]
            if us.done then table.remove(upgradeStates, i)
            else
                BP_PLACER.Update(us, frame, resources)
                i = i + 1
            end
        end
    end
    local reserve = consolidateOn and 1 or 0
    if #freeT2Cons > reserve then TryAssignUpgrades() end
end

local function UpdateConsolidation(frame, resources)
    if consolidateOn then
        if frame % CONSOLIDATE_SCAN == 0 or #windBlocks == 0 then
            ScanWindBlocks()
        end
        -- Converting wind beats upgrading another grid at the cap, so every free
        -- T2 con starts a job immediately rather than one per scan.
        while #freeT2Cons > 0 and #windBlocks > 0 do
            local conID = freeT2Cons[1]
            if not spGetUnitDefID(conID) then
                table.remove(freeT2Cons, 1)
            elseif StartConsolidation(conID, resources) then
                table.remove(freeT2Cons, 1)
            else
                break
            end
        end
    end

    local i = 1
    while i <= #consolidateJobs do
        local cs = consolidateJobs[i]
        if cs.done then
            if cs.builderID and spGetUnitDefID(cs.builderID) then
                freeT2Cons[#freeT2Cons + 1] = cs.builderID
            end
            table.remove(consolidateJobs, i)
        else
            BP_PLACER.Update(cs, frame, resources)
            i = i + 1
        end
    end
end

local function UpdateCapstones(frame, resources)
    if #pendingCapstones > 0 and #freeT2Cons > 0 then TryAssignCapstones() end
    local i = 1
    while i <= #capstoneJobs do
        local cs = capstoneJobs[i]
        if cs.done then
            if cs.builderID and spGetUnitDefID(cs.builderID) then
                freeT2Cons[#freeT2Cons + 1] = cs.builderID
            end
            table.remove(capstoneJobs, i)
        else
            BP_PLACER.Update(cs, frame, resources)
            i = i + 1
        end
    end
end

local energyNet = nil   -- smoothed energy income - pull, e/s

local function ReadResources()
    local _, m,  ms,  mp, mi = pcall(Spring.GetTeamResources, myTeamID, "metal")
    local _, em, ems, ep, ei = pcall(Spring.GetTeamResources, myTeamID, "energy")
    local net = (ei or 0) - (ep or 0)
    energyNet = energyNet and (energyNet + NET_SMOOTH * (net - energyNet)) or net
    return {
        metal  = m  or 0, metalStorage  = ms  or 1000,
        energy = em or 0, energyStorage = ems or 1000,
        metalIncome = mi or 0, metalPull = mp or 0,
        energyIncome = ei or 0, energyPull = ep or 0,
        energyNet = energyNet,
    }
end

-- Grid interrupts: the placer's metal interrupt, and an energy interrupt that fires on the
-- projected level instead of the current one (see ENERGY_LOOKAHEAD).  Same name and
-- priority as the placer's, so interrupt episodes behave exactly as before.
local earlyEnergyChecks = 0   -- checks that fired only because of the look-ahead
local function EnergyLookahead(state, res, frame)
    local st = res.energyStorage
    if not st or st <= 0 then return false end
    local projected = res.energy + math.min(0, res.energyNet or 0) * ENERGY_LOOKAHEAD
    local fires = projected / st < ENERGY_LOW
    if fires and res.energy / st >= ENERGY_LOW then earlyEnergyChecks = earlyEnergyChecks + 1 end
    return fires
end

GridInterrupts = function()
    return {
        {name = "energy", priority = 2, buildType = "energy", check = EnergyLookahead},
        BP_PLACER.GRID_INTERRUPTS[2],          -- metal, unchanged
    }
end

function widget:GameFrame(frame)
    currentFrame = frame
    if not myTeamID or not BP_PLACER then return end

    if startPending and frame >= START_FRAME then BeginBuildOrder() end
    if not distState then return end

    MaybeQueueCon2(frame)
    FirePendingStops(frame)

    if frame % 10 ~= 0 then return end

    local resources = ReadResources()
    if frame % 1800 == 0 and earlyEnergyChecks > 0 then
        Spring.Echo(string.format("[MC] energy look-ahead: %d grid checks fired early this minute "
            .. "(net %.0f e/s, stored %.0f)", earlyEnergyChecks, energyNet or 0, resources.energy))
        earlyEnergyChecks = 0
    end

    -- Retire finished and dead nano assignments first, so freed nanos are
    -- available to everything that asks for one later in this same tick.
    NANO.Sweep()

    UpdateHandoff(frame, resources)
    MaybeQueueVehicleLab(frame)
    UpdateGrids(frame, resources)
    CheckCapPressure()
    UpdateRetrofits(frame, resources)
    UpdateConsolidation(frame, resources)
    UpdateCapstones(frame, resources)

    if frame % RECLAIM_EVERY == 0 then UpdateWindReclaim() end
    UpdateSpendPressure(resources)

    GateLabReclaim(frame)
    -- Phases before the placer runs: the commander must be out of the builder pool
    -- before Update hands it a claim it is about to abandon.
    UpdateCommanderPhase(frame, resources)
    if frame % NANO_REBALANCE == 0 then UpdateNanoBalance(frame) end

    if not distState.done then
        BP_PLACER.Update(distState, frame, resources)
    end
end
